<a href="https://colab.research.google.com/github/mahathirumalathi97-web/Cross-Market-Analysis/blob/main/Cross_Analysis_Markets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#                                            CROSS MARKET ANALYSIS

# 1. Crypto Currency Coins

In [ ]:
url:"https://api.coingecko.com/api/v3/coins/markets?vs_currency=inr&per_page=250&order=market_cap_desc&page=1&sparkline=False"

In [ ]:
import requests
records=[]
for i in range(1,6):
     url=f"https://api.coingecko.com/api/v3/coins/markets?vs_currency=inr&per_page=250&order=market_cap_desc&page=1&sparkline=False"
     response=requests.get(url)
     if response.status_code==200:
         data=response.json()
         records.extend(data)

In [ ]:
import pandas as pd
df=pd.DataFrame(records)
df.head()

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,6875086.00,137533521841053,1,137533521841053,5.450599e+12,7008786.00,...,2.000299e+07,2.100000e+07,11187013.00,-38.54404,2025-10-06T18:57:42.558Z,3993.420000,1.720604e+05,2013-07-05T00:00:00.000Z,None,2026-03-17T07:21:40.819Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,215865.00,26051322901823,2,26051322901823,3.053418e+12,219458.00,...,1.206919e+08,NaN,431946.00,-50.02504,2025-08-24T19:21:03.333Z,28.130000,7.672485e+05,2015-10-20T00:00:00.000Z,"{'times': 40.97226828917929, 'currency': 'btc'...",2026-03-17T07:21:40.871Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,92.43,17013893382289,3,17519209061672,9.727131e+12,92.47,...,1.895378e+11,NaN,105.52,-12.41115,2025-01-25T16:51:57.989Z,36.860000,1.507425e+02,2015-03-02T00:00:00.000Z,None,2026-03-17T07:21:41.264Z
3,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,141.32,8651956559302,4,14128737104661,5.163743e+11,147.66,...,9.998570e+10,1.000000e+11,313.99,-54.99110,2025-07-21T15:02:00.541Z,0.159343,8.859055e+04,2013-08-16T00:00:00.000Z,None,2026-03-17T07:21:41.364Z
4,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,62408.00,8510222229970,5,8510222229970,1.456654e+11,63268.00,...,1.363579e+08,2.000000e+08,121422.00,-48.60271,2025-10-13T08:41:24.131Z,2.580000,2.414366e+06,2017-10-19T00:00:00.000Z,None,2026-03-17T07:21:40.526Z

In [ ]:
import pandas as pd
df = pd.DataFrame(records)
df['last_updated'] = pd.to_datetime(df['last_updated'])
df['date'] = df['last_updated'].dt.date
df = df.drop('last_updated', axis=1)
df = df[['id', 'symbol', 'name', 'current_price', 'market_cap', 'market_cap_rank', 'total_volume', 'circulating_supply', 'total_supply', 'ath', 'atl', 'date']]

In [ ]:
df.head()

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,date
0,bitcoin,btc,Bitcoin,6875086.00,137533521841053,1,5.450599e+12,2.000299e+07,2.000299e+07,11187013.00,3993.420000,2026-03-17
1,ethereum,eth,Ethereum,215865.00,26051322901823,2,3.053418e+12,1.206919e+08,1.206919e+08,431946.00,28.130000,2026-03-17
2,tether,usdt,Tether,92.43,17013893382289,3,9.727131e+12,1.840709e+11,1.895378e+11,105.52,36.860000,2026-03-17
3,ripple,xrp,XRP,141.32,8651956559302,4,5.163743e+11,6.122783e+10,9.998570e+10,313.99,0.159343,2026-03-17
4,binancecoin,bnb,BNB,62408.00,8510222229970,5,1.456654e+11,1.363579e+08,1.363579e+08,121422.00,2.580000,2026-03-17

In [ ]:
df.to_csv("crypto_market_data.csv",index=False)

AttributeError: 'DataFrame' object has no attribute 'read_csv'

# 2. Top 3 Coins - Historical prices

In [ ]:
url="https://api.coingecko.com/api/v3/coins/bitcoin/market_chart?vs_currency=inr&days=365"

In [ ]:
import pandas as pd
df=pd.DataFrame(records)

In [ ]:
import requests
records=[]
for i in range(1,6):
     url=f"https://api.coingecko.com/api/v3/coins/markets?vs_currency=inr&per_page=250&order=market_cap_desc&page=1&sparkline=False"
     response=requests.get(url)
     if response.status_code==200:
         data=response.json()
         records.extend(data)

In [ ]:
import requests
from datetime import datetime
import pandas as pd

top_3 = ["bitcoin","ethereum","tether"]
all_data = []

for coin_id in top_3:
    url = f"https://api.coingecko.com/api/v3/coins/{coin_id}/market_chart?vs_currency=inr&days=365"

    data = requests.get(url)
    if data.status_code == 200:

        hist_data = data.json()

        if "prices" in hist_data:
           for price in hist_data["prices"]:
            timestamp = price[0]
            price_inr = price[1]

            date = datetime.fromtimestamp(timestamp / 1000).strftime("%Y-%m-%d")

            all_data.append({
                "coin_id": coin_id,
                "date": date,
                "price_inr": price_inr
            })

In [ ]:
price_df = pd.DataFrame(all_data)
price_df

      coin_id        date     price_inr
0     bitcoin  2025-03-07  7.841737e+06
1     bitcoin  2025-03-08  7.562231e+06
2     bitcoin  2025-03-09  7.503958e+06
3     bitcoin  2025-03-10  7.035608e+06
4     bitcoin  2025-03-11  6.882112e+06
...       ...         ...           ...
1093   tether  2026-03-03  9.156693e+01
1094   tether  2026-03-04  9.201194e+01
1095   tether  2026-03-05  9.213504e+01
1096   tether  2026-03-06  9.179148e+01
1097   tether  2026-03-06  9.169499e+01

[1098 rows x 3 columns]

In [ ]:
import pandas as pd
price_df = pd.DataFrame(all_data)
price_df.to_csv("top3_daily_price_1year_inr.csv",index=False)

Oil prices (WTI Crude)

# 3. Oil Prices (WTI Crude)

In [ ]:
import pandas as pd
oil_df=pd.read_csv("https://raw.githubusercontent.com/datasets/oil-prices/main/data/wti-daily.csv")
oil_df

             Date  Price
0      1986-01-02  25.56
1      1986-01-03  26.00
2      1986-01-06  26.53
3      1986-01-07  25.85
4      1986-01-08  25.87
...           ...    ...
10104  2026-02-24  65.62
10105  2026-02-25  65.30
10106  2026-02-26  65.10
10107  2026-02-27  66.96
10108  2026-03-02  71.13

[10109 rows x 2 columns]

In [ ]:
import pandas as pd
from datetime import datetime

start_date_str = '2020-01-01'
end_date_str = '2026-01-31'

start_date = pd.to_datetime(start_date_str)
end_date = pd.to_datetime(end_date_str)

oil_df['Date'] = pd.to_datetime(oil_df['Date'])

filtered_oil_df = oil_df[(oil_df['Date'] >= start_date) & (oil_df['Date'] <= end_date)]
filtered_oil_df

            Date  Price
8569  2020-01-02  61.17
8570  2020-01-03  63.00
8571  2020-01-06  63.27
8572  2020-01-07  62.70
8573  2020-01-08  59.65
...          ...    ...
10084 2026-01-26  60.46
10085 2026-01-27  62.04
10086 2026-01-28  62.75
10087 2026-01-29  64.77
10088 2026-01-30  64.50

[1520 rows x 2 columns]

In [ ]:
filtered_oil_df.to_csv('oil_df.csv',index=False)

# 4.Stock Prices (Yahoo Finance API)

In [ ]:
import yfinance as yf
import pandas as pd

# Choose indices
tickers = ["^GSPC", "^IXIC", "^NSEI"]
start_date = "2020-01-01"
end_date = "2026-01-12"

# Download historical data
stocks_df = yf.download(tickers, start=start_date, end=end_date, group_by="ticker")
stocks_df.head()

/tmp/ipykernel_483/1369541528.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  stocks_df = yf.download(tickers, start=start_date, end=end_date, group_by="ticker")
[*********************100%***********************]  3 of 3 completed

Ticker            ^GSPC                                                       \
Price              Open         High          Low        Close        Volume
Date
2020-01-01          NaN          NaN          NaN          NaN           NaN
2020-01-02  3244.669922  3258.139893  3235.530029  3257.850098  3.459930e+09
2020-01-03  3226.360107  3246.149902  3222.340088  3234.850098  3.484700e+09
2020-01-06  3217.550049  3246.840088  3214.639893  3246.280029  3.702460e+09
2020-01-07  3241.860107  3244.909912  3232.429932  3237.179932  3.435910e+09

Ticker            ^IXIC                                                       \
Price              Open         High          Low        Close        Volume
Date
2020-01-01          NaN          NaN          NaN          NaN           NaN
2020-01-02  9039.459961  9093.429688  9010.889648  9092.190430  2.862700e+09
2020-01-03  8976.429688  9065.759766  8976.429688  9020.769531  2.586520e+09
2020-01-06  8943.500000  9072.410156  8943.500000  9071.469727  2.810450e+09
2020-01-07  9076.639648  9091.929688  9042.549805  9068.580078  2.381740e+09

Ticker             ^NSEI
Price               Open          High           Low         Close    Volume
Date
2020-01-01  12202.150391  12222.200195  12165.299805  12182.500000  304100.0
2020-01-02  12198.549805  12289.900391  12195.250000  12282.200195  407700.0
2020-01-03  12261.099609  12265.599609  12191.349609  12226.650391  428800.0
2020-01-06  12170.599609  12179.099609  11974.200195  11993.049805  396500.0
2020-01-07  12079.099609  12152.150391  12005.349609  12052.950195  447800.0

In [ ]:
import pandas as pd
df=stocks_df['^IXIC'].reset_index()
df.columns=pd.MultiIndex.from_product([['^IXIC'],list(df.columns)])
display(df)

          ^IXIC                                                          \
           Date          Open          High           Low         Close
0    2020-01-01           NaN           NaN           NaN           NaN
1    2020-01-02   9039.459961   9093.429688   9010.889648   9092.190430
2    2020-01-03   8976.429688   9065.759766   8976.429688   9020.769531
3    2020-01-06   8943.500000   9072.410156   8943.500000   9071.469727
4    2020-01-07   9076.639648   9091.929688   9042.549805   9068.580078
...         ...           ...           ...           ...           ...
1558 2026-01-05  23449.669922  23476.509766  23332.230469  23395.820312
1559 2026-01-06  23446.960938  23559.150391  23389.570312  23547.169922
1560 2026-01-07  23544.890625  23723.369141  23504.210938  23584.279297
1561 2026-01-08  23548.880859  23558.169922  23353.460938  23480.019531
1562 2026-01-09  23496.210938  23721.150391  23426.480469  23671.349609


            Volume
0              NaN
1     2.862700e+09
2     2.586520e+09
3     2.810450e+09
4     2.381740e+09
...            ...
1558  8.737320e+09
1559  9.012640e+09
1560  8.396920e+09
1561  7.723140e+09
1562  8.124420e+09

[1563 rows x 6 columns]

In [ ]:
stocks_df['^IXIC'].reset_index().to_csv('IXIC.csv',index=False)

In [ ]:
import pandas as pd
df=stocks_df["^GSPC"].reset_index()
df.columns=pd.MultiIndex.from_product([["^GSPC"],list(df.columns)])
display(df)

          ^GSPC                                                      \
           Date         Open         High          Low        Close
0    2020-01-01          NaN          NaN          NaN          NaN
1    2020-01-02  3244.669922  3258.139893  3235.530029  3257.850098
2    2020-01-03  3226.360107  3246.149902  3222.340088  3234.850098
3    2020-01-06  3217.550049  3246.840088  3214.639893  3246.280029
4    2020-01-07  3241.860107  3244.909912  3232.429932  3237.179932
...         ...          ...          ...          ...          ...
1558 2026-01-05  6892.189941  6920.379883  6891.560059  6902.049805
1559 2026-01-06  6908.029785  6948.689941  6904.020020  6944.819824
1560 2026-01-07  6945.069824  6965.689941  6919.189941  6920.930176
1561 2026-01-08  6914.109863  6931.279785  6899.330078  6921.459961
1562 2026-01-09  6927.830078  6978.359863  6917.640137  6966.279785


            Volume
0              NaN
1     3.459930e+09
2     3.484700e+09
3     3.702460e+09
4     3.435910e+09
...            ...
1558  5.771930e+09
1559  5.509680e+09
1560  5.214480e+09
1561  5.333200e+09
1562  5.163900e+09

[1563 rows x 6 columns]

In [ ]:
stocks_df["^GSPC"].reset_index().to_csv('GSPC.csv',index=False)

In [ ]:
import pandas as pd
df=stocks_df["^NSEI"].reset_index()
df.columns=pd.MultiIndex.from_product([["^NSEI"],list(df.columns)])
display(df)

          ^NSEI                                                          \
           Date          Open          High           Low         Close
0    2020-01-01  12202.150391  12222.200195  12165.299805  12182.500000
1    2020-01-02  12198.549805  12289.900391  12195.250000  12282.200195
2    2020-01-03  12261.099609  12265.599609  12191.349609  12226.650391
3    2020-01-06  12170.599609  12179.099609  11974.200195  11993.049805
4    2020-01-07  12079.099609  12152.150391  12005.349609  12052.950195
...         ...           ...           ...           ...           ...
1558 2026-01-05  26333.699219  26373.199219  26210.050781  26250.300781
1559 2026-01-06  26189.699219  26273.949219  26124.750000  26178.699219
1560 2026-01-07  26143.099609  26187.150391  26067.900391  26140.750000
1561 2026-01-08  26106.500000  26133.199219  25858.449219  25876.849609
1562 2026-01-09  25840.400391  25940.599609  25623.000000  25683.300781


        Volume
0     304100.0
1     407700.0
2     428800.0
3     396500.0
4     447800.0
...        ...
1558  338800.0
1559  383000.0
1560  338200.0
1561  328500.0
1562  348800.0

[1563 rows x 6 columns]

In [ ]:
stocks_df["^NSEI"].reset_index().to_csv('NSEI.csv',index=False)

In [ ]:
import pandas as pd
import glob
import os

In [ ]:
df_list = ['IXIC.csv','GSPC.csv','NSEI.csv']

In [ ]:
df_list = []

for file in df_list:
    df = pd.read_csv(file)
    df_list.append(df)

In [ ]:
import pandas as pd

filenames_to_load = ['IXIC.csv','GSPC.csv','NSEI.csv']

dataframes_to_concat = []

for file_name in filenames_to_load:
    df_temp = pd.read_csv(file_name)
    dataframes_to_concat.append(df_temp)

combined_df = pd.concat(dataframes_to_concat, ignore_index=True)

In [ ]:
import pandas as pd
import yfinance as yf

all_stocks_data = []

for ticker_symbol in tickers:

    temp_df = stocks_df[ticker_symbol].copy()
    temp_df = temp_df.reset_index()

    temp_df.columns = [col.lower() for col in temp_df.columns]

    temp_df['ticker'] = ticker_symbol

    if 'adj close' in temp_df.columns:
        temp_df = temp_df.drop(columns=['adj close'])

    all_stocks_data.append(temp_df)

df_final_stocks = pd.concat(all_stocks_data, ignore_index=True)

sql_columns = ['date', 'open', 'high', 'low', 'close', 'volume', 'ticker']
df_final_stocks = df_final_stocks[sql_columns]

display(df_final_stocks.head())

df = df_final_stocks

,date,open,high,low,close,volume,ticker
0,2020-01-01,NaN,NaN,NaN,NaN,NaN,^GSPC
1,2020-01-02,3244.669922,3258.139893,3235.530029,3257.850098,3.459930e+09,^GSPC
2,2020-01-03,3226.360107,3246.149902,3222.340088,3234.850098,3.484700e+09,^GSPC
3,2020-01-06,3217.550049,3246.840088,3214.639893,3246.280029,3.702460e+09,^GSPC
4,2020-01-07,3241.860107,3244.909912,3232.429932,3237.179932,3.435910e+09,^GSPC

In [ ]:
combined_df.to_csv("combined_file.csv", index=False)

# Connect to DataFrame into SQL

In [1]:
import sqlite3

In [2]:
import sqlite3
import pandas as pd
conn = sqlite3.connect('Market.db')
print("Connected to in-memory database")

Connected to in-memory database

In [ ]:
import pandas as pd
df=pd.read_csv("/content/crypto_market_data.csv")

# 1.Cryptocurrencies Table created

In [ ]:
cursor = conn.cursor()

cursor.execute('''
    CREATE TABLE Cryptocurrencies (
       id VARCHAR(50) PRIMARY KEY, ---- Unique ID from CoinGecko (e.g., “bitcoin”)
       symbol VARCHAR(50), ---Short symbol (e.g., BTC, ETH)
       name  VARCHAR(100), ---Full name of the cryptocurrency
       current_price DECIMAL(18, 6), --Current trading price INR
       market_cap BIGINT, ----Market capitalization (INR)
       market_cap_rank INT, ---Rank by market capitalization
       total_volume BIGINT, ---Trading volume (24h, INR)
       circulating_supply DECIMAL(20, 6), ---Coins in circulation
       total_supply DECIMAL(20, 6), ---Total supply (if available)
       ath DECIMAL(18, 6), ----All-time high price (INR)
       atl DECIMAL(18, 6),---All-time low price (INR)
       date DATE ----Last updated
    )
''')

OperationalError: table Cryptocurrencies already exists

# Insert into Table

In [ ]:
import pandas as pd
df = pd.read_csv("crypto_market_data.csv")

insert_query = """INSERT OR IGNORE INTO Cryptocurrencies(id, symbol, name, current_price, market_cap,
       market_cap_rank, total_volume, circulating_supply, total_supply,
       ath, atl, date) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)"""

for i, row in df.iterrows():
    values = (row['id'],row['symbol'],row['name'],row['current_price'],row['market_cap'],row['market_cap_rank'],
              row['total_volume'],row['circulating_supply'],row['total_supply'],row['ath'],row['atl'],row['date'])
    cursor.execute(insert_query,values)
conn.commit()

# Insert After Viewing Values

In [ ]:
import pandas as pd

cursor.execute("select * from Cryptocurrencies")
rows = cursor.fetchall()
columns = [i[0] for i in cursor.description]
df = pd.DataFrame(rows,columns=columns)
df.head()

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,date
0,bitcoin,btc,Bitcoin,6752113.00,135452989368039,1,6.964142e+12,1.999774e+07,1.999774e+07,11187013.00,3993.420000,2026-03-04
1,ethereum,eth,Ethereum,197165.00,23870911582429,2,2.887631e+12,1.206922e+08,1.206922e+08,431946.00,28.130000,2026-03-04
2,tether,usdt,Tether,92.16,16931975188269,3,1.039388e+13,1.837127e+11,1.891796e+11,105.52,36.860000,2026-03-04
3,binancecoin,bnb,BNB,60569.00,8273840305082,4,1.387843e+11,1.363586e+08,1.363586e+08,121422.00,2.580000,2026-03-04
4,ripple,xrp,XRP,133.23,8155553694422,5,3.945364e+11,6.109038e+10,9.998571e+10,313.99,0.159343,2026-03-04

In [ ]:
df.isnull().sum()

id                    0
symbol                0
name                  0
current_price         0
market_cap            0
market_cap_rank       0
total_volume          9
circulating_supply    0
total_supply          0
ath                   0
atl                   0
date                  0
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
pd.read_sql(
    "SELECT count(*) as total_rows FROM Cryptocurrencies ",
    conn
)

   total_rows
0         250

In [ ]:
import pandas as pd
df=pd.read_csv("/content/top3_daily_price_1year_inr.csv")

# 2. Crypto_prices Table Created

In [ ]:
cursor.execute('''
    CREATE TABLE top3_daily_price_1year_inr(
      coin_id TEXT VARCHAR(50),-----  FOREIGN KEY (coin_id) REFERENCES Cryptocurrencies (id)
      date DATE,
      price_inr DECIMAL(18, 6)

   )
''')

# Insert into Table

In [ ]:
insert_query = """INSERT INTO top3_daily_price_1year_inr (coin_id ,date,price_inr) VALUES (?,?,?)"""

# Ensure the correct DataFrame (price_df) is used for insertion
df = price_df

for i, row in df.iterrows():
    values = (row['coin_id'],row['date'],row['price_inr'])
    cursor.execute(insert_query,values)
conn.commit()

In [ ]:
df.isnull().sum()

coin_id      0
date         0
price_inr    0
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
pd.read_sql(
    "SELECT count(*)as total_rows FROM top3_daily_price_1year_inr ", conn)

   total_rows
0        1464

# Insert After Viewing Values

In [ ]:
import pandas as pd

cursor.execute("select * from top3_daily_price_1year_inr")
rows = cursor.fetchall()
columns = [i[0] for i in cursor.description]
df = pd.DataFrame(rows,columns=columns)
df.head()

   coin_id        date     price_inr
0  bitcoin  2025-03-07  7.841737e+06
1  bitcoin  2025-03-08  7.562231e+06
2  bitcoin  2025-03-09  7.503958e+06
3  bitcoin  2025-03-10  7.035608e+06
4  bitcoin  2025-03-11  6.882112e+06

3.OIL _ PRICES

In [ ]:
import pandas as pd
df=pd.read_csv("/content/oil_df.csv")

# 3. Oil_Prices Table Created

In [ ]:
cursor.execute('''
    CREATE TABLE oil_prices(
       date DATE PRIMARY KEY,
      price_inr DECIMAL(18, 6) -- WTI crude oil price per barrel (INR)
   )
''')

conn.commit()

# Insert into Table

In [ ]:
import pandas as pd

insert_query = """INSERT or ignore INTO oil_prices (date,price_inr) VALUES (?,?)"""
for i, row in df.iterrows():
    values = (row['Date'],row['Price'])
    cursor.execute(insert_query,values)
conn.commit()

In [ ]:
df.isnull().sum()

Date     0
Price    0
dtype: int64

# Insert After Viewing Values

In [ ]:
import pandas as pd
cursor.execute("select * from oil_prices")
rows = cursor.fetchall()
columns = [i[0] for i in cursor.description]
df = pd.DataFrame(rows,columns=columns)
df.head()

         date  price_inr
0  2020-01-02      61.17
1  2020-01-03      63.00
2  2020-01-06      63.27
3  2020-01-07      62.70
4  2020-01-08      59.65

# 4. Stock _ Prices Table Created

In [ ]:
df.to_csv("stock_prices.csv",index=False)

In [ ]:
import pandas as pd
df=pd.read_csv("/content/stock_prices.csv")
df.head()

,date,open,high,low,close,volume,ticker
0,2020-01-01,NaN,NaN,NaN,NaN,NaN,^GSPC
1,2020-01-02,3244.669922,3258.139893,3235.530029,3257.850098,3.459930e+09,^GSPC
2,2020-01-03,3226.360107,3246.149902,3222.340088,3234.850098,3.484700e+09,^GSPC
3,2020-01-06,3217.550049,3246.840088,3214.639893,3246.280029,3.702460e+09,^GSPC
4,2020-01-07,3241.860107,3244.909912,3232.429932,3237.179932,3.435910e+09,^GSPC

In [ ]:
df.isnull().sum()

date        0
open      168
high      168
low       168
close     168
volume    168
ticker      0
dtype: int64

In [ ]:
df['date'] = pd.to_datetime(df['date'])
df['date'] = df['date'].dt.strftime('%Y-%m-%d')

In [ ]:
df.dropna(inplace=True)

In [ ]:
cursor = conn.cursor()

cursor.execute('''
    CREATE TABLE stock_prices(
      date DATE,---Trading date
      open decimal(18,6),-----Opening price
      high decimal(18,6),----Highest price of the day
      low decimal(18,6),----Lowest price of the day
      close decimal,----Closing price
      volume bigint,----Trading volume
      ticker varchar(20)---Stock index symbol (e.g., ^GSPC, ^IXIC)


   )
''')

OperationalError: table stock_prices already exists

# Insert into Table

In [ ]:
df = df_final_stocks

df.dropna(inplace=True)

df['date'] = pd.to_datetime(df['date'])
df['date'] = df['date'].dt.strftime('%Y-%m-%d')

insert_query = """INSERT or ignore INTO stock_prices (date,open,high,low,close,volume,ticker) VALUES (?,?,?,?,?,?,?)"""

for i, row in df.iterrows():
    values = (row['date'],row['open'],row['high'],row['low'],row['close'],row['volume'],row['ticker'])
    cursor.execute(insert_query,values)
conn.commit()

# Insert After Viewing Values

In [ ]:
import pandas as pd
cursor.execute("select * from stock_prices")
rows = cursor.fetchall()
columns = [i[0] for i in cursor.description]
df = pd.DataFrame(rows,columns=columns)
df.head()

,date,open,high,low,close,volume,ticker
0,2020-01-02,3244.669922,3258.139893,3235.530029,3257.850098,3459930000,^GSPC
1,2020-01-03,3226.360107,3246.149902,3222.340088,3234.850098,3484700000,^GSPC
2,2020-01-06,3217.550049,3246.840088,3214.639893,3246.280029,3702460000,^GSPC
3,2020-01-07,3241.860107,3244.909912,3232.429932,3237.179932,3435910000,^GSPC
4,2020-01-08,3238.590088,3267.070068,3236.669922,3253.050049,3726840000,^GSPC

In [ ]:
df['ticker'].value_counts()

ticker
^GSPC    1514
^IXIC    1514
^NSEI    1493
Name: count, dtype: int64

In [ ]:
df.to_csv("stock_prices.csv",index=False)

# SQL Queries

# Cryptocurrencies - (1 to 5)

# 1.Find the highest oil price in the last 5 years.

In [ ]:
import pandas as pd
pd.read_sql("""SELECT name, market_cap
    FROM Cryptocurrencies
    ORDER BY market_cap DESC
    LIMIT 3;""", conn)

       name       market_cap
0   Bitcoin  135452989368039
1  Ethereum   23870911582429
2    Tether   16931975188269

# 2.Get the average oil price per year.

In [ ]:
pd.read_sql("""SELECT
   id,symbol,name,circulating_supply,total_supply,
   ROUND((circulating_supply * 100.0) / total_supply, 2) AS supply_percentage
   FROM Cryptocurrencies
   WHERE total_supply IS NOT NULL
   AND total_supply > 0
   AND circulating_supply >= 0.9 * total_supply
   ORDER BY supply_percentage DESC;
   """,conn)

,id,symbol,name,circulating_supply,total_supply,supply_percentage
0,bitcoin,btc,Bitcoin,1.999771e+07,1.999771e+07,100.00
1,ethereum,eth,Ethereum,1.206922e+08,1.206922e+08,100.00
2,binancecoin,bnb,BNB,1.363586e+08,1.363586e+08,100.00
3,tron,trx,TRON,9.474143e+10,9.474158e+10,100.00
4,figure-heloc,figr_heloc,Figure Heloc,1.555925e+10,1.555925e+10,100.00
...,...,...,...,...,...,...
134,avalanche-2,avax,Avalanche,4.317720e+08,4.634411e+08,93.17
135,kucoin-shares,kcs,KuCoin,1.321550e+08,1.421550e+08,92.97
136,convex-finance,cvx,Convex Finance,9.175823e+07,9.995560e+07,91.80
137,solana,sol,Solana,5.697669e+08,6.215985e+08,91.66
138,conflux-token,cfx,Conflux,5.159697e+09,5.732659e+09,90.01

# 3.Show oil prices during COVID crash (March–April 2020).

In [ ]:
pd.read_sql("""SELECT
    id,symbol,name,current_price,ath,
    ROUND((current_price / ath) * 100, 2) AS percent_of_ath
    FROM Cryptocurrencies
    WHERE ath IS NOT NULL
    AND ath > 0
    AND current_price >= 0.9 * ath
    ORDER BY percent_of_ath DESC;
    """, conn)

,id,symbol,name,current_price,ath,percent_of_ath
0,onyc,onyc,Onchain Yield Coin,99.64,99.83,99.81
1,frax-usd,frxusd,Frax USD,92.20,92.38,99.81
2,ripple-usd,rlusd,Ripple USD,92.20,92.39,99.79
3,bfusd,bfusd,BFUSD,92.14,92.33,99.79
4,hastra-prime,prime,PRIME,94.02,94.22,99.79
5,usd1-wlfi,usd1,USD1,92.14,92.34,99.78
6,hashnote-usyc,usyc,Circle USYC,103.14,103.37,99.78
7,usdd,usdd,USDD,92.23,92.43,99.78
8,gho,gho,GHO,92.25,92.45,99.78
9,usds,usds,USDS,92.20,92.41,99.77
10,ylds,ylds,YLDS,92.19,92.40,99.77
11,agora-dollar,ausd,AUSD,92.19,92.41,99.76
12,janus-henderson-anemoy-treasury-fund,jtrsy,Janus Henderson Anemoy Treasury Fund,101.00,101.27,99.73
13,ousg,ousg,OUSG,10546.92,10576.45,99.72
14,blackrock-usd-institutional-digital-liquidity-...,buidl,BlackRock USD Institutional Digital Liquidity ...,92.13,92.40,99.71
15,superstate-short-duration-us-government-securi...,ustb,Superstate Short Duration U.S. Government Secu...,1014.26,1017.21,99.71
16,spiko-us-t-bills-money-market-fund,ustbl,Spiko US T-Bills Money Market Fund,99.14,99.43,99.71
17,fidelity-digital-interest-token,fdit,Fidelity Digital Interest Token,92.14,92.41,99.71
18,paypal-usd,pyusd,PayPal USD,92.17,92.48,99.66
19,dai,dai,Dai,92.18,92.50,99.65
20,resolv-usr,usr,Resolv USR,92.09,92.44,99.62
21,re-protocol-reusd,reusd,Re Protocol reUSD,98.11,98.49,99.61
22,janus-henderson-anemoy-aaa-clo-fund,jaaa,Janus Henderson Anemoy AAA CLO Fund,94.49,94.91,99.56
23,falcon-finance,usdf,Falcon USD,91.98,92.45,99.49
24,ethena-usde,usde,Ethena USDe,92.14,92.91,99.17
25,usda-2,usda,USDa,89.60,90.58,98.92
26,frax,frax,Legacy Frax Dollar,90.85,91.87,98.89
27,avant-usd,avusd,Avant USD,92.16,93.96,98.08
28,gusd,gusd,GUSD,92.20,94.03,98.05
29,astherus-usdf,usdf,Aster USDF,92.06,94.12,97.81
30,eutbl,eutbl,Spiko EU T-Bills Money Market Fund,112.32,115.38,97.35
31,nusd-2,nusd,Neutrl USD,92.02,94.55,97.32
32,coco-2,coco,coco,13.71,14.11,97.17
33,ondo-us-dollar-yield,usdy,Ondo US Dollar Yield,102.52,105.80,96.90
34,pleasing-usd,pusd,Pleasing USD,92.18,95.47,96.55
35,usx,usx,USX,92.18,95.56,96.46
36,usdtb,usdtb,USDtb,92.12,95.66,96.30
37,euro-coin,eurc,EURC,107.27,111.47,96.23
38,crvusd,crvusd,crvUSD,91.91,96.91,94.84
39,theo-short-duration-us-treasury-fund,thbill,Theo Short Duration US Treasury Fund,93.49,98.66,94.76
40,the9bit,9bit,The9bit,1.89,2.00,94.50
41,leo-token,leo,LEO Token,837.68,888.26,94.31
42,first-digital-usd,fdusd,First Digital USD,92.37,100.07,92.31
43,adi-token,adi,ADI,286.06,313.06,91.38
44,tether-gold,xaut,Tether Gold,471445.00,514631.00,0.00
45,pax-gold,paxg,PAX Gold,475310.00,516779.00,0.00
46,apollo-diversified-credit-securitize-fund,acred,Apollo Diversified Credit Securitize Fund,100873.00,101338.00,0.00

# 4.Find the lowest price of oil in the last 10 years.

In [ ]:
pd.read_sql("""SELECT
ROUND(AVG(market_cap_rank), 2) AS avg_market_cap_rank
FROM Cryptocurrencies
WHERE total_volume >= 1000000000
AND market_cap_rank IS NOT NULL;
""", conn)

   avg_market_cap_rank
0               104.64

# 5.Calculate the volatility of oil prices (max-min difference per year).

In [ ]:
pd.read_sql("""SELECT
id,symbol,name,date
FROM Cryptocurrencies
ORDER BY date DESC
LIMIT 5;
  """,conn    )

            id symbol      name        date
0      bitcoin    btc   Bitcoin  2026-03-04
1     ethereum    eth  Ethereum  2026-03-04
2       tether   usdt    Tether  2026-03-04
3  binancecoin    bnb       BNB  2026-03-04
4       ripple    xrp       XRP  2026-03-04

# Crypto_prices (daily prices of top coins - (6 - 10)

# 6.Find the highest daily price of Bitcoin in the last 365 days.

In [ ]:
pd.read_sql("""SELECT
coin_id, MAX(price_inr) AS highest_price_last_365_days
FROM top3_daily_price_1year_inr
WHERE coin_id = 'bitcoin'
AND date >= DATE('now', '-365 day');
""", conn)

   coin_id  highest_price_last_365_days
0  bitcoin                 1.107047e+07

# 7.Calculate the average daily price of Ethereum in the past 1 year.

In [ ]:
pd.read_sql("""Select
  avg(price_inr)as avg_price_last_365_days
  from top3_daily_price_1year_inr
  where coin_id = 'ethereum'
  and date >= DATE('now', '-366 day');
  """,conn)

   avg_price_last_365_days
0            263118.516321

# 8.Show the daily price trend of Bitcoin in January 2025.

In [ ]:
pd.read_sql("""Select
 date,coin_id,price_inr
 from top3_daily_price_1year_inr
 where coin_id = 'bitcoin'
 and date between '2025-01-01' and '2025-12-31'
 order by date;
 """,conn)

           date  coin_id     price_inr
0    2025-03-05  bitcoin  7.615008e+06
1    2025-03-05  bitcoin  7.615008e+06
2    2025-03-06  bitcoin  7.869430e+06
3    2025-03-06  bitcoin  7.869430e+06
4    2025-03-07  bitcoin  7.841737e+06
..          ...      ...           ...
599  2025-12-29  bitcoin  7.887771e+06
600  2025-12-30  bitcoin  7.835388e+06
601  2025-12-30  bitcoin  7.835388e+06
602  2025-12-31  bitcoin  7.936951e+06
603  2025-12-31  bitcoin  7.936951e+06

[604 rows x 3 columns]

# 9.Find the coin with the highest average price over 1 year.

In [ ]:
pd.read_sql("""Select
 coin_id, avg(price_inr)as avg_price
 from top3_daily_price_1year_inr
 group by coin_id
 order by avg_price desc
 limit 1;
 """,conn)

   coin_id     avg_price
0  bitcoin  8.647879e+06

# 10.Get the % change in Bitcoin’s price between Sep 2024 and Sep 2025.

In [ ]:
pd.read_sql("""SELECT
  ((MAX(price_inr) - MIN(price_inr)) / MIN(price_inr)) * 100 AS pct_change
   FROM top3_daily_price_1year_inr
   WHERE coin_id='bitcoin'
   AND date BETWEEN '2025-01-27' AND '2026-01-26';
   """, conn)

   pct_change
0   67.798154

# Oil_prices (11 -15)

# 11.Find the highest oil price in the last 5 years.

In [ ]:
pd.read_sql("""Select
  max(price_inr) as highest_price from oil_prices
  where date >= DATE('now', '-5 years');
  """,conn)

   highest_price
0         123.64

# 12.Get the average oil price per year.

In [ ]:
pd.read_sql("""SELECT
  strftime('%Y', date) AS year,
  ROUND(AVG(price_inr), 2) AS avg_price
  FROM oil_prices
  GROUP BY year
  ORDER BY year;
  """,conn)

   year  avg_price
0  2020      39.16
1  2021      68.14
2  2022      94.90
3  2023      77.58
4  2024      76.63
5  2025      65.39
6  2026      60.04

# 13.Show oil prices during COVID crash (March–April 2020).

In [ ]:
pd.read_sql("""SELECT
  date,price_inr
  FROM oil_prices
  WHERE date BETWEEN '2020-03-01' AND '2020-04-30'
  ORDER BY date;
  """,conn)

          date  price_inr
0   2020-03-02      46.78
1   2020-03-03      47.27
2   2020-03-04      46.78
3   2020-03-05      45.90
4   2020-03-06      41.14
5   2020-03-09      31.05
6   2020-03-10      34.47
7   2020-03-11      33.13
8   2020-03-12      31.56
9   2020-03-13      31.72
10  2020-03-16      28.96
11  2020-03-17      26.96
12  2020-03-18      20.48
13  2020-03-19      25.09
14  2020-03-20      19.48
15  2020-03-23      23.33
16  2020-03-24      21.03
17  2020-03-25      20.75
18  2020-03-26      16.60
19  2020-03-27      15.48
20  2020-03-30      14.10
21  2020-03-31      20.51
22  2020-04-01      20.28
23  2020-04-02      25.18
24  2020-04-03      28.36
25  2020-04-06      26.21
26  2020-04-07      23.54
27  2020-04-08      24.97
28  2020-04-09      22.90
29  2020-04-13      22.36
30  2020-04-14      20.15
31  2020-04-15      19.96
32  2020-04-16      19.82
33  2020-04-17      18.31
34  2020-04-20     -36.98
35  2020-04-21       8.91
36  2020-04-22      13.64
37  2020-04-23      15.06
38  2020-04-24      15.99
39  2020-04-27      12.17
40  2020-04-28      12.40
41  2020-04-29      15.04
42  2020-04-30      19.23

# 14.Find the lowest price of oil in the last 10 years.

In [ ]:
pd.read_sql("""Select
   min(price_inr) as lowest_price from oil_prices
   where date >= DATE('now', '-10 years');
   """,conn)

   lowest_price
0        -36.98

# 15.Calculate the volatility of oil prices (max-min difference per year).

In [ ]:
pd.read_sql("""SELECT
  strftime('%Y', date) AS year,
  MAX(price_inr) AS max_price,
  MIN(price_inr) AS min_price,
  ROUND(MAX(price_inr) - MIN(price_inr), 2) AS volatility
  FROM oil_prices
  GROUP BY year
  ORDER BY year;
  """,conn)

   year  max_price  min_price  volatility
0  2020      63.27     -36.98      100.25
1  2021      85.64      47.47       38.17
2  2022     123.64      71.05       52.59
3  2023      93.67      66.61       27.06
4  2024      87.69      66.73       20.96
5  2025      80.73      55.44       25.29
6  2026      64.77      56.01        8.76

# stock_prices - (16 - 20)

# 16.Get all stock prices for a given ticker

In [ ]:
pd.read_sql("""
SELECT *
FROM stock_prices
GROUP BY ticker
ORDER BY date;
""",conn)

,date,open,high,low,close,volume,ticker
0,2020-01-01,12202.150391,12222.200195,12165.299805,12182.500000,304100,^NSEI
1,2020-01-02,3244.669922,3258.139893,3235.530029,3257.850098,3459930000,^GSPC
2,2020-01-02,9039.459961,9093.429688,9010.889648,9092.190430,2862700000,^IXIC

# 17.Find the highest closing price for NASDAQ (^IXIC)

In [ ]:
pd.read_sql("""
SELECT MAX(close) AS highest_close
FROM stock_prices
WHERE ticker = '^IXIC';
""",conn)

   highest_close
0   23958.470703

# 18.List top 5 days with highest price difference (high - low) for S&P 500 (^GSPC)

In [ ]:
pd.read_sql("""
SELECT date, (high - low) AS price_diff
FROM stock_prices
WHERE ticker = '^GSPC'
ORDER BY price_diff DESC
LIMIT 5;
""",conn)

         date  price_diff
0  2025-04-09  532.909668
1  2025-04-07  411.529785
2  2025-04-08  357.050293
3  2025-04-10  237.879883
4  2025-11-20  236.300293

# 19.Get monthly average closing price for each ticker

In [ ]:
pd.read_sql("""
SELECT
  ticker,
  strftime('%Y-%m', date) AS month,
  AVG(close) AS avg_close
FROM stock_prices
GROUP BY ticker, month
ORDER BY ticker, month;
""",conn)

    ticker    month     avg_close
0    ^GSPC  2020-01   3278.202858
1    ^GSPC  2020-02   3277.314183
2    ^GSPC  2020-03   2652.393632
3    ^GSPC  2020-04   2761.975226
4    ^GSPC  2020-05   2919.608484
..     ...      ...           ...
214  ^NSEI  2025-09  24942.674982
215  ^NSEI  2025-10  25494.083519
216  ^NSEI  2025-11  25894.834396
217  ^NSEI  2025-12  25997.738725
218  ^NSEI  2026-01  26086.428850

[219 rows x 3 columns]

# 20.Get average trading volume of NSEI in 2024

In [ ]:
pd.read_sql("""
SELECT AVG(volume) AS avg_volume_2024
FROM stock_prices
WHERE ticker = '^NSEI'
  AND date BETWEEN '2024-01-01' AND '2024-12-31';
  """,conn)

   avg_volume_2024
0    313560.162602

# Based on 4 tables - (21 - 30)

# 21. Find the Average Bitcoin vs stock volume average price.

In [ ]:
pd.read_sql("""Select
coin_id, avg(price_inr)as avg_price,
avg(s.volume) AS avg_stock_volume
from top3_daily_price_1year_inr t
join stock_prices s on t.date = s.date
where coin_id = 'bitcoin'
;""",conn)

   coin_id     avg_price  avg_stock_volume
0  bitcoin  8.954734e+06      4.900857e+09

# 22.Check if oil prices with S&P 500 high (correlation idea). 2025

In [ ]:
pd.read_sql("""SELECT
avg(o.price_inr) as avg_oil,
avg(s.high) AS avg_stock_high
FROM top3_daily_price_1year_inr t
JOIN oil_prices o ON t.date = o.date
JOIN stock_prices s ON t.date = s.date
WHERE t.date BETWEEN '2025-01-01' AND '2025-12-31';
""",conn)

    avg_oil  avg_stock_high
0  63.80329    17230.095307

# 23.Find the average price and avgerage low stock price for 2025-2026.

In [ ]:
pd.read_sql("""SELECT
avg(price_inr) as avg_price,
avg(s.low) AS avg_stock_low
FROM top3_daily_price_1year_inr t
JOIN stock_prices s ON t.date = s.date
WHERE t.date BETWEEN '2025-01-01' AND '2026-12-31';
""",conn)

      avg_price  avg_stock_low
0  4.613177e+06   17176.555672

# 24.compare the oil price and the average volume stock price between 2020 and 2025."

In [ ]:
pd.read_sql("""SELECT
o.date AS oil_date,
avg(o.price_inr) as avg_price,
avg(s.volume) AS avg_stock_volume
FROM oil_prices o
JOIN stock_prices s ON o.date = s.date
WHERE s.date BETWEEN '2020-01-01' AND '2025-12-31';
""",conn)

     oil_date  avg_price  avg_stock_volume
0  2020-01-02  70.250736      3.448263e+09

# 25.Retrieve top3 historical prices and stock ticker, volume, and date for stock data between 2024 and 2025.

In [ ]:
pd.read_sql("""SELECT
avg (price_inr) as price_inr,
s.ticker AS stock_ticker,
s.volume AS stock_volume
FROM top3_daily_price_1year_inr t
JOIN stock_prices s ON t.date = s.date
WHERE t.date BETWEEN '2024-01-01' AND '2025-12-31'
ORDER BY t.date;
""",conn)

      price_inr stock_ticker  stock_volume
0  4.624048e+06        ^NSEI        305900

# 26.Find the average close and oil price for the stock ticker 'NSEI' between 2020 and 2025.

In [ ]:
pd.read_sql("""SELECT
 AVG(s.close) AS avg_stock_close,
 AVG(price_inr) AS avg_price
FROM oil_prices o
JOIN stock_prices s ON o.date = s.date
WHERE s.ticker = '^NSEI'
  AND o.date BETWEEN '2020-01-01' AND '2025-12-31';
""",conn)

   avg_stock_close  avg_price
0     18521.070923  70.211371

# 27.Compare the monthly average close prices of stock prices with oil prices.

In [ ]:
pd.read_sql("""SELECT
oil_prices.date,  ticker,
strftime('%Y-%m', stock_prices.date) AS month,
AVG(close) AS avg_close
from oil_prices
join stock_prices on oil_prices.date=stock_prices.date
GROUP BY ticker, month
ORDER BY ticker, month;
""",conn)

           date ticker    month     avg_close
0    2020-01-02  ^GSPC  2020-01   3278.202858
1    2020-02-03  ^GSPC  2020-02   3277.314183
2    2020-03-02  ^GSPC  2020-03   2652.393632
3    2020-04-01  ^GSPC  2020-04   2761.975226
4    2020-05-01  ^GSPC  2020-05   2919.608484
..          ...    ...      ...           ...
214  2025-09-02  ^NSEI  2025-09  24957.799944
215  2025-10-01  ^NSEI  2025-10  25507.420215
216  2025-11-03  ^NSEI  2025-11  25887.726677
217  2025-12-01  ^NSEI  2025-12  25997.738725
218  2026-01-02  ^NSEI  2026-01  26076.408529

[219 rows x 4 columns]

# 28.Find the top 5 stock tickers with the largest price difference between high and low on the same date

In [ ]:
pd.read_sql("""SELECT
 ticker,
(high - low) AS price_diff
FROM top3_daily_price_1year_inr t
JOIN stock_prices s ON t.date = s.date
WHERE ticker = '^GSPC'
ORDER BY price_diff DESC
LIMIT 5;
""",conn)

  ticker  price_diff
0  ^GSPC  532.909668
1  ^GSPC  532.909668
2  ^GSPC  532.909668
3  ^GSPC  532.909668
4  ^GSPC  411.529785

#29.Find the top 2 tickers and close in stock prices.

In [ ]:
pd.read_sql("""SELECT
 s.ticker AS stock_ticker,
 s.close AS stock_close
FROM stock_prices s
WHERE s.ticker IN ('^NSEI', '^GSPC')
 ORDER BY  s.ticker
 limit 10;
""",conn)

  stock_ticker  stock_close
0        ^GSPC  3257.850098
1        ^GSPC  3234.850098
2        ^GSPC  3246.280029
3        ^GSPC  3237.179932
4        ^GSPC  3253.050049
5        ^GSPC  3274.699951
6        ^GSPC  3265.350098
7        ^GSPC  3288.129883
8        ^GSPC  3283.149902
9        ^GSPC  3289.290039

# 30.Find the top 5 stock tickers with the highest price difference (calculated as high - low) for the ticker 'GSPC' (S&P 500) from the stock prices table.

In [ ]:
pd.read_sql("""SELECT
 ticker,
(high - low) AS price_diff
FROM stock_prices s
WHERE ticker = '^GSPC'
ORDER BY price_diff DESC
LIMIT 5;
""",conn)

  ticker  price_diff
0  ^GSPC  532.909668
1  ^GSPC  411.529785
2  ^GSPC  357.050293
3  ^GSPC  237.879883
4  ^GSPC  236.300293

# Install streamlit

In [3]:
!pip install -q streamlit
!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared-linux-amd64
import subprocess
subprocess.Popen(["./cloudflared-linux-amd64", "tunnel", "--url", "http://localhost:8501"])
!nohup /content/cloudflared-linux-amd64 tunnel --url http://localhost:8501 &

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 69.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 94.4 MB/s eta 0:00:00
--2026-03-17 09:56:58--  https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
Resolving github.com (github.com)... 140.82.116.3
Connecting to github.com (github.com)|140.82.116.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/cloudflare/cloudflared/releases/download/2026.3.0/cloudflared-linux-amd64 [following]
--2026-03-17 09:56:58--  https://github.com/cloudflare/cloudflared/releases/download/2026.3.0/cloudflared-linux-amd64
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/106867604/731ab2f8-6b77-4adb-a7b3-1104525e9d72?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-17T10%3A45%3A03Z&rscd=attachment%3B+filename%3Dcloudflared-linux-amd64&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-17T09%3A44%3A28Z&ske=2026-03-17T10%3A45%3A03Z&sks=b&skv=2018-11-09&sig=8QmCsLjjI2jn4hqfpKEqBXPwP37XEywTa7O6JTtsOks%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mzc0MzEwNSwibmJmIjoxNzczNzQxMzA1LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.Gp9HPkZfNep9l_UZWTs0uWUUTa4Kv_GvU6WU3u2HEEc&response-content-disposition=attachment%3B%20filename%3Dcloudflared-linux-amd64&response-content-type=application%2Foctet-stream [following]
--2026-03-17 09:56:58--  https://release-assets.githubusercontent.com/github-production-release-asset/106867604/731ab2f8-6b77-4adb-a7b3-1104525e9d72?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-17T10%3A45%3A03Z&rscd=attachment%3B+filename%3Dcloudflared-linux-amd64&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-17T09%3A44%3A28Z&ske=2026-03-17T10%3A45%3A03Z&sks=b&skv=2018-11-09&sig=8QmCsLjjI2jn4hqfpKEqBXPwP37XEywTa7O6JTtsOks%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3Mzc0MzEwNSwibmJmIjoxNzczNzQxMzA1LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.Gp9HPkZfNep9l_UZWTs0uWUUTa4Kv_GvU6WU3u2HEEc&response-content-disposition=attachment%3B%20filename%3Dcloudflared-linux-amd64&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 39667364 (38M) [application/octet-stream]
Saving to: ‘cloudflared-linux-amd64’

cloudflared-linux-a 100%[===================>]  37.83M  --.-KB/s    in 0.1s

2026-03-17 09:56:58 (278 MB/s) - ‘cloudflared-linux-amd64’ saved [39667364/39667364]

nohup: appending output to 'nohup.out'

In [4]:
%%writefile app.py
import streamlit as st
import sqlite3
import pandas as pd
import datetime as dt
conn = sqlite3.connect("Market.db")
st.sidebar.title("Navigation")

menu = st.sidebar.selectbox(
    "Select a page:",
    ["Home", "Cross Market Overview", "SQL Query Runner", "Top 3 Crypto Analysis"]
)

# -------------------------
# HOME PAGE
# -------------------------
if menu == "Home":
    st.title("📊 Cross Market Analysis")
    st.write("Welcome to the Cross Market Analysis Dashboard")

# -------------------------
# CROSS MARKET OVERVIEW
# -------------------------
elif menu == "Cross Market Overview":
    st.title("📈 Cross Market Overview")


    st.subheader("Select Date Range")
    start_date = st.date_input("Start Date", value=pd.to_datetime("2020-01-01"))
    end_date = st.date_input("End Date", value=pd.to_datetime("today"))

    btc_q = f"""
    SELECT date, current_price AS bitcoin_price
    FROM Cryptocurrencies
    WHERE date BETWEEN '{start_date.strftime('%Y-%m-%d')}' AND '{end_date.strftime('%Y-%m-%d')}'
    """

    oil_q = f"""
    SELECT date, price_inr AS oil_price
    FROM oil_prices
    WHERE date BETWEEN '{start_date.strftime('%Y-%m-%d')}' AND '{end_date.strftime('%Y-%m-%d')}'
    """

    sp_q = f"""
    SELECT date, close AS sp500_close
    FROM stock_prices
    WHERE ticker = '^GSPC'
      AND date BETWEEN '{start_date.strftime('%Y-%m-%d')}' AND '{end_date.strftime('%Y-%m-%d')}'
    """

    nifty_q = f"""
    SELECT date, close AS nifty_close
    FROM stock_prices
    WHERE ticker = '^NSEI'
      AND date BETWEEN '{start_date.strftime('%Y-%m-%d')}' AND '{end_date.strftime('%Y-%m-%d')}'
    """

    btc_df = pd.read_sql(btc_q, conn)
    oil_df = pd.read_sql(oil_q, conn)
    sp_df = pd.read_sql(sp_q, conn)
    nifty_df = pd.read_sql(nifty_q, conn)

    if not btc_df.empty and not oil_df.empty and not sp_df.empty and not nifty_df.empty:
        col1, col2, col3, col4 = st.columns(4)
        col1.metric("Bitcoin Avg", round(btc_df["bitcoin_price"].mean(), 2))
        col2.metric("Oil Avg", round(oil_df["oil_price"].mean(), 2))
        col3.metric("S&P 500 Avg", round(sp_df["sp500_close"].mean(), 2))
        col4.metric("NIFTY Avg", round(nifty_df["nifty_close"].mean(), 2))

        # -------------------------
        # 📅 Daily Market Snapshot (Separate Date Ranges)
        # -------------------------
        st.subheader("📅 Daily Market Snapshot (Separate Date Ranges)")

        # --- Bitcoin ---
        st.markdown("### 🪙 Bitcoin Date Range")
        btc_start = st.date_input("Bitcoin Start Date", dt.date(2026, 3,4), key="btc_start")
        btc_end   = st.date_input("Bitcoin End Date", dt.date(2026, 3, 4), key="btc_end")

        btc_snap = pd.read_sql(f"""
        SELECT date, current_price AS bitcoin_price
        FROM Cryptocurrencies
        WHERE id = 'bitcoin'
          AND date BETWEEN '{btc_start}' AND '{btc_end}'
        ORDER BY date;
        """, conn)

        st.dataframe(btc_snap, use_container_width=True)

        # --- Oil ---
        st.markdown("### 🛢️ Oil Date Range")
        oil_start = st.date_input("Oil Start Date", dt.date(2020, 1, 2), key="oil_start")
        oil_end   = st.date_input("Oil End Date", dt.date(2026, 1, 26), key="oil_end")

        oil_snap = pd.read_sql(f"""
        SELECT date, price_inr AS oil_price
        FROM oil_prices
        WHERE date BETWEEN '{oil_start}' AND '{oil_end}'
        ORDER BY date;
        """, conn)

        st.dataframe(oil_snap, use_container_width=True)

        # --- NIFTY ---
        st.markdown("### 📈 NIFTY Date Range")
        nifty_start = st.date_input("NIFTY Start Date", dt.date(2020, 1, 1), key="nifty_start")
        nifty_end   = st.date_input("NIFTY End Date", dt.date(2026, 1, 9), key="nifty_end")

        nifty_snap = pd.read_sql(f"""
        SELECT date, open, high, low, close, volume
        FROM stock_prices
        WHERE ticker = '^NSEI'
          AND date BETWEEN '{nifty_start}' AND '{nifty_end}'
        ORDER BY date;
        """, conn)

        st.dataframe(nifty_snap, use_container_width=True)

    else:
        st.warning("No data available for selected date range.")
# -------------------------
# SQL QUERY RUNNER
# -------------------------
elif menu == "SQL Query Runner":
    st.title("🔎 SQL Query Runner")

    conn = sqlite3.connect("Market.db")

    queries = {
       "1. Find the top 3 cryptocurrencies by market cap":
        "SELECT name, market_cap FROM cryptocurrencies ORDER BY market_cap DESC LIMIT 3;",

    "2. List all coins where circulating supply exceeds 90% of total supply":
        "SELECT name, circulating_supply, total_supply FROM cryptocurrencies WHERE circulating_supply >= 0.9 * total_supply;",

    "3. Get coins that are within 10% of their all-time-high (ATH)":
        "SELECT name, current_price, ath FROM cryptocurrencies WHERE current_price >= 0.9 * ath;",

    "4. Find the average market cap rank of coins with volume above 1B":
        "SELECT AVG(market_cap_rank) AS avg_rank FROM cryptocurrencies WHERE total_volume > 1000000000;",

    "5. Get the most recently updated coin":
       "SELECT id,symbol,name,date FROM Cryptocurrencies ORDER BY date DESC LIMIT 1; ",

    "6.Find the highest daily price of Bitcoin in the last 365 days.":
    "SELECT coin_id, MAX(price_inr) AS highest_price_last_365_days FROM top3_daily_price_1year_inr WHERE coin_id = 'bitcoin' AND date >= DATE('now', '-365 day');",

    "7.Calculate the average daily price of Ethereum in the past 1 year.":
    "Select  avg(price_inr)as avg_price_last_365_days from top3_daily_price_1year_inr where coin_id = 'ethereum' and date >= DATE('now', '-366 day');",

    "8.Show the daily price trend of Bitcoin in January 2025.":
    "Select date,coin_id,price_inr  from top3_daily_price_1year_inr  where coin_id = 'bitcoin' and date between '2025-01-01' and '2025-12-31'   order by date;",

    "9.Find the coin with the highest average price over 1 year.":
     "Select coin_id, avg(price_inr)as avg_price from top3_daily_price_1year_inr group by coin_id order by avg_price desc limit 1;",

    "10.Get the % change in Bitcoin’s price between Sep 2024 and Sep 2025.":
    "SELECT ((MAX(price_inr) - MIN(price_inr)) / MIN(price_inr)) * 100 AS pct_change FROM top3_daily_price_1year_inr WHERE coin_id='bitcoin'AND date BETWEEN '2025-01-27' AND '2026-01-26';",

    "11.Find the highest oil price in the last 5 years.":
    "Select max(price_inr) as highest_price from oil_prices where date >= DATE('now', '-5 years');",
    "12.Get the average oil price per year.":
    " SELECT strftime('%Y', date) AS year, ROUND(AVG(price_inr), 2) AS avg_price FROM oil_prices GROUP BY year ORDER BY year;",

   " 13.Show oil prices during COVID crash (March–April 2020).":
    "SELECT date, price_inr FROM oil_prices WHERE date BETWEEN '2020-03-01' AND '2020-04-30' ORDER BY date;",

    "14.Find the lowest price of oil in the last 10 years.":
     "Select min(price_inr) as lowest_price from oil_prices where date >= DATE('now', '-10 years');",

    "15.Calculate the volatility of oil prices (max-min difference per year).":
    "SELECT strftime('%Y', date) AS year, MAX(price_inr) AS max_price, MIN(price_inr) AS min_price, ROUND(MAX(price_inr) - MIN(price_inr), 2) AS volatility FROM oil_prices GROUP BY year  ORDER BY year;",

    "16.Get all stock prices for a given ticker":
    "SELECT * FROM stock_prices GROUP BY ticker ORDER BY date;",

    "17.Find the highest closing price for NASDAQ (^IXIC)":
    "SELECT MAX(close) AS highest_close FROM stock_prices WHERE ticker = '^IXIC';",

    "18.List top 5 days with highest price difference (high - low) for S&P 500 (^GSPC)":
    "SELECT date, (high - low) AS price_diff FROM stock_prices WHERE ticker = '^GSPC' ORDER BY price_diff;",

    "19.Get monthly average closing price for each ticker":
    "SELECT ticker, strftime('%Y-%m', date) AS month, AVG(close) AS avg_close FROM stock_prices GROUP BY ticker, month ORDER BY ticker, month;",

    "20.Get average trading volume of NSEI in 2024":
    "SELECT AVG(volume) AS avg_volume_2024 FROM stock_prices WHERE ticker = '^NSEI' AND date BETWEEN '2024-01-01' AND '2024-12-31';",

    "21. Find the Average Bitcoin vs stock volume average price.":
    "Select  coin_id, avg(price_inr)as avg_price, avg(s.volume) AS avg_stock_volume from top3_daily_price_1year_inr t join stock_prices s on t.date = s.date where coin_id = 'bitcoin';",

    "22.Check if oil prices with S&P 500 high (correlation idea). 2025.":
    "SELECT avg(o.price_inr) as avg_oil, avg(s.high) AS avg_stock_high FROM top3_daily_price_1year_inr t JOIN oil_prices o ON t.date = o.date JOIN stock_prices s ON t.date = s.date WHERE t.date BETWEEN '2025-01-01' AND '2025-12-31';",

    "23.Find the average price and avgerage low stock price for 2025-2026.":
    "SELECT avg(price_inr) as avg_price, avg(s.low) AS avg_stock_low FROM top3_daily_price_1year_inr t JOIN stock_prices s ON t.date = s.date WHERE t.date BETWEEN '2025-01-01' AND '2026-12-31';",

    "24.compare the oil price and the average volume stock price between 2020 and 2025.":
    "SELECT o.date AS oil_date, avg(o.price_inr) as avg_price, avg(s.volume) AS avg_stock_volume FROM oil_prices o JOIN stock_prices s ON o.date = s.date WHERE s.date BETWEEN '2020-01-01' AND '2025-12-31';",

    "25.Retrieve top3 historical prices and stock ticker, volume, and date for stock data between 2024 and 2025.":
    "SELECT avg (price_inr) as price_inr, s.ticker AS stock_ticker, s.volume AS stock_volume FROM top3_daily_price_1year_inr t JOIN stock_prices s ON t.date = s.date WHERE t.date BETWEEN '2024-01-01' AND '2025-12-31' ORDER BY t.date;",

    "26.Find the average close and oil price for the stock ticker 'NSEI' between 2020 and 2025.":
    "SELECT AVG(s.close) AS avg_stock_close, AVG(price_inr) AS avg_price FROM oil_prices o JOIN stock_prices s ON o.date = s.date WHERE s.ticker = '^NSEI'   AND o.date BETWEEN '2020-01-01' AND '2025-12-31';",

    "27.Compare the monthly average close prices of stock prices with oil prices.":
    "SELECT oil_prices.date,  ticker, strftime('%Y-%m', stock_prices.date) AS month, AVG(close) AS avg_close from oil_prices join stock_prices on oil_prices.date=stock_prices.date GROUP BY ticker, month ORDER BY ticker, month;",

    "28.Find the top 5 stock tickers with the largest price difference between high and low on the same date":
    "SELECT ticker,(high - low) AS price_diff FROM top3_daily_price_1year_inr t JOIN stock_prices s ON t.date = s.date WHERE ticker = '^GSPC' ORDER BY price_diff DESC Limit 5;",

    "29.Find the top 2 tickers and close in stock prices.":
    "SELECT   s.ticker AS stock_ticker,  s.close AS stock_close FROM stock_prices s  WHERE s.ticker IN ('^NSEI', '^GSPC')  ORDER BY  s.ticker limit 10;",

    "30.Find the top 5 stock tickers with the highest price difference (calculated as high - low) for the ticker 'GSPC' (S&P 500) from the stock prices table.":
    "SELECT  ticker, (high - low) AS price_diff FROM stock_prices s WHERE ticker = '^GSPC' ORDER BY price_diff DESC LIMIT 5;"
    }

    selected_question = st.selectbox("Select a Question", list(queries.keys()))
    st.text_area("SQL Query", queries[selected_question], height=80)

    if st.button("Run Query"):
        try:
            df = pd.read_sql(queries[selected_question], conn)
            st.success("Query executed successfully!")
            st.dataframe(df)
        except Exception as e:
            st.error(f"Error: {e}")

# -------------------------
# TOP 3 CRYPTO ANALYSIS
# -------------------------
elif menu == "Top 3 Crypto Analysis":
    st.title("🪙 Top 3 Crypto Analysis")

    conn = sqlite3.connect("Market.db")

    coins = {
        "Bitcoin (BTC)": "bitcoin",
        "Ethereum (ETH)": "ethereum",
        "Tether (USDT)": "tether"
    }

    selected_coin_name = st.selectbox("Select a Coin", list(coins.keys()))
    selected_coin = coins[selected_coin_name]

    col1, col2 = st.columns(2)
    with col1:
        start_date = st.date_input("Start date", dt.date(2025, 3, 5))
    with col2:
        end_date = st.date_input("End date", dt.date(2026, 3, 4))

    if st.button("Show Price"):
        query = """
        SELECT DISTINCT date, price_inr
        FROM top3_daily_price_1year_inr
        WHERE coin_id = ?
          AND date BETWEEN ? AND ?
        ORDER BY date ASC
        """

        df = pd.read_sql(query, conn, params=(selected_coin, str(start_date), str(end_date)))

        if df.empty:
            st.warning("No data found for this period.")
        else:
            st.success(f"Daily price for {selected_coin_name}")
            st.dataframe(df)

Writing app.py

In [5]:
!streamlit run /content/app.py &>/content/logs.txt &

In [6]:
!grep -o 'https://.*\.trycloudflare.com' nohup.out | head -n 1 | xargs -I {} echo "Your tunnel url {}"

Your tunnel url https://deluxe-downtown-featuring-heavily.trycloudflare.com