<a href="https://colab.research.google.com/github/mahathirumalathi97-web/Cross-Market-Analysis/blob/main/Global_Literacy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Global Literacy & Education Trends

In [ ]:
# Data Collection

In [ ]:
url="https://ourworldindata.org/grapher/"

In [ ]:
import pandas as pd
df1_adult = pd.read_csv("/content/literacy_rate_adults.csv")
df2_youth = pd.read_csv("/content/literacy_rate_youth.csv")
df3_illiterate = pd.read_csv("https://ourworldindata.org/grapher/literate-and-illiterate-world-population.csv?v=1&csvType=full&useColumnShortNames=true",storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})
df4_GDP = pd.read_csv("/content/gdp_per_capita.csv")
df5_schooling = pd.read_csv("/content/literacy_vs_schooling.csv")

In [ ]:
# Save the file

In [ ]:
import pandas as pd
df1_adult.to_csv("Adult.csv",index=False)
df2_youth.to_csv("Youth.csv",index=False)
df3_illiterate.to_csv("Illiterate.csv",index=False)
df4_GDP.to_csv("GDP.csv",index=False)
df5_schooling.to_csv("Schooling.csv",index=False)

In [ ]:
df1_adult.head()

,entity,code,year,adult_literacy_rate__population_15plus_years__both_sexes__pct__lr_ag15t99
0,Afghanistan,AFG,1979,18.00000
1,Afghanistan,AFG,2011,31.00000
2,Afghanistan,AFG,2015,33.75384
3,Afghanistan,AFG,2021,37.00000
4,Albania,ALB,2001,99.00000

# Shape

In [ ]:
{
   df1_adult.shape,
   df2_youth.shape,
   df3_illiterate.shape,
   df4_GDP.shape,
   df5_schooling.shape
}

{(1725, 4), (2002, 6), (2059, 5), (5365, 7), (7240, 5)}

# Info

In [ ]:
{
   df1_adult.info(),
   df2_youth.info(),
   df3_illiterate.info(),
   df4_GDP.info(),
   df5_schooling.info()
}

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1725 entries, 0 to 1724
Data columns (total 4 columns):
 #   Column                                                                     Non-Null Count  Dtype
---  ------                                                                     --------------  -----
 0   entity                                                                     1725 non-null   object
 1   code                                                                       996 non-null    object
 2   year                                                                       1725 non-null   int64
 3   adult_literacy_rate__population_15plus_years__both_sexes__pct__lr_ag15t99  1725 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 54.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2002 entries, 0 to 2001
Data columns (total 6 columns):
 #   Column                                                                  Non-Null Count  Dtype
---  ------                                                                  --------------  -----
 0   entity                                                                  2002 non-null   object
 1   code                                                                    1260 non-null   object
 2   year                                                                    2002 non-null   int64
 3   youth_literacy_rate__population_15_24_years__male__pct__lr_ag15t24_m    1925 non-null   float64
 4   youth_literacy_rate__population_15_24_years__female__pct__lr_ag15t24_f  2002 non-null   float64
 5   owid_region                                                             1211 non-null   object
dtypes: float64(2), int64(1), object(3)
memory usage: 94.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2059 entries, 0 to 2058
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   entity           2059 non-null   object
 1   code             1326 non-null   object
 2   year             2059 non-null   int64
 3   illiteracy_rate  2059 non-null   float64
 4   literacy_rate    2059 non-null   float64
dtypes: float64(2), int64(1), object(2)
memory usage: 80.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7240 entries, 0 to 7239
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   entity             7240 non-null   object
 1   code               7240 non-null   object
 2   year               7240 non-null   int64
 3   ny_gdp_pcap_pp_kd  7240 non-null   float64
 4   owid_region        6785 non-null   object
dtypes: float64(1), int64(1), object(3)
memory usage: 282.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5365 entries, 0 to 5364
Data columns (total 7 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   entity                                                        5365 non-null   object
 1   code                                                          4475 non-null   object
 2   year                                                          5365 non-null   int64
 3   literacy_rate                                                 2000 non-null   float64
 4   mf_youth_and_adults__15_64_years__average_years_of_education  3668 non-null   float64
 5   population_historical                                         4760 non-null   float64
 6   owid_region                                                   4472 non-null   object
dtypes: float64(3), int64(1), object(3)
memory usage: 293.5+ KB

{None}

# columns

In [ ]:
df1_adult = df1_adult.rename(columns={'adult_literacy_rate__population_15plus_years__both_sexes__pct__lr_ag15t99': 'adult_literacy_rate_population','entity':'Country_X'})
df2_youth = df2_youth.rename(columns={'youth_literacy_rate__population_15_24_years__male__pct__lr_ag15t24_m':'male','youth_literacy_rate__population_15_24_years__female__pct__lr_ag15t24_f':'female','entity':'Country_Y','owid_region':'owid_region_y'})
df3_illiterate = df3_illiterate.rename(columns={'entity':'Country_Z'})
df4_GDP = df4_GDP.rename(columns={'ny_gdp_pcap_pp_kd':'gdp_per_capita','entity':'Country_A','owid_region':'owid_region_a'})
df5_schooling = df5_schooling.rename(columns={'entity':'Country_B','mf_youth_and_adults__15_64_years__average_years_of_education':'youth_adult_yr_edu','owid_region':'owid_region_b'})

In [ ]:
[
   df1_adult.columns,
   df2_youth.columns,
   df3_illiterate.columns,
   df4_GDP.columns,
   df5_schooling.columns
]

[Index(['Country_X', 'code', 'year', 'adult_literacy_rate_population'], dtype='object'),
 Index(['Country_Y', 'code', 'year', 'male', 'female', 'owid_region_y'], dtype='object'),
 Index(['Country_Z', 'code', 'year', 'illiteracy_rate', 'literacy_rate'], dtype='object'),
 Index(['Country_A', 'code', 'year', 'gdp_per_capita', 'owid_region_a'], dtype='object'),
 Index(['Country_B', 'code', 'year', 'literacy_rate', 'youth_adult_yr_edu',
        'population_historical', 'owid_region_b'],
       dtype='object')]

# Dtypes

In [ ]:
[
    df1_adult.dtypes,
    df2_youth.dtypes,
    df3_illiterate.dtypes,
    df4_GDP.dtypes,
    df5_schooling.dtypes
]

[Country_X                          object
 code                               object
 year                                int64
 adult_literacy_rate_population    float64
 dtype: object,
 Country_Y         object
 code              object
 year               int64
 male             float64
 female           float64
 owid_region_y     object
 dtype: object,
 Country_Z           object
 code                object
 year                 int64
 illiteracy_rate    float64
 literacy_rate      float64
 dtype: object,
 Country_A          object
 code               object
 year                int64
 gdp_per_capita    float64
 owid_region_a      object
 dtype: object,
 Country_B                 object
 code                      object
 year                       int64
 literacy_rate            float64
 youth_adult_yr_edu       float64
 population_historical    float64
 owid_region_b             object
 dtype: object]

# null values

In [ ]:
[
    df1_adult.isnull().sum(),
    df2_youth.isnull().sum(),
    df3_illiterate.isnull().sum(),
    df4_GDP.isnull().sum(),
    df5_schooling.isnull().sum()
]

[Country_X                           0
 code                              729
 year                                0
 adult_literacy_rate_population      0
 dtype: int64,
 Country_Y          0
 code             742
 year               0
 male              77
 female             0
 owid_region_y    791
 dtype: int64,
 Country_Z            0
 code               733
 year                 0
 illiteracy_rate      0
 literacy_rate        0
 dtype: int64,
 Country_A           0
 code                0
 year                0
 gdp_per_capita      0
 owid_region_a     455
 dtype: int64,
 Country_B                   0
 code                      890
 year                        0
 literacy_rate            3365
 youth_adult_yr_edu       1697
 population_historical     605
 owid_region_b             893
 dtype: int64]

In [ ]:
[
    df1_adult.isnull().sum()/len(df1_adult)*100,
    df2_youth.isnull().sum()/len(df2_youth)*100,
    df3_illiterate.isnull().sum()/len(df3_illiterate)*100,
    df4_GDP.isnull().sum()/len(df4_GDP)*100,
    df5_schooling.isnull().sum()/len(df5_schooling)*100
]

[Country_X                          0.00000
 code                              42.26087
 year                               0.00000
 adult_literacy_rate_population     0.00000
 dtype: float64,
 Country_Y         0.000000
 code             37.062937
 year              0.000000
 male              3.846154
 female            0.000000
 owid_region_y    39.510490
 dtype: float64,
 Country_Z           0.000000
 code               35.599806
 year                0.000000
 illiteracy_rate     0.000000
 literacy_rate       0.000000
 dtype: float64,
 Country_A         0.00000
 code              0.00000
 year              0.00000
 gdp_per_capita    0.00000
 owid_region_a     6.28453
 dtype: float64,
 Country_B                 0.000000
 code                     16.589003
 year                      0.000000
 literacy_rate            62.721342
 youth_adult_yr_edu       31.630941
 population_historical    11.276794
 owid_region_b            16.644921
 dtype: float64]

In [ ]:
df5_schooling["youth_adult_yr_edu"].fillna(df5_schooling["youth_adult_yr_edu"].mean(), inplace=True)
df5_schooling["literacy_rate"].fillna(df5_schooling["literacy_rate"].median(), inplace=True)
df5_schooling["population_historical"].fillna(df5_schooling["population_historical"].mean(), inplace=True)
df2_youth["male"].fillna(df2_youth["male"].mean(), inplace=True)
df2_youth["owid_region_y"].fillna(df2_youth["owid_region_y"].mode()[0], inplace=True)

/tmp/ipykernel_458/3933844224.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df5_schooling["youth_adult_yr_edu"].fillna(df5_schooling["youth_adult_yr_edu"].mean(), inplace=True)
/tmp/ipykernel_458/3933844224.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df5_schooling["literacy_rate"].fillna(df5_schooling["literacy_rate"].median(), inplace=True)
/tmp/ipykernel_458/3933844224.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df5_schooling["population_historical"].fillna(df5_schooling["population_historical"].mean(), inplace=True)
/tmp/ipykernel_458/3933844224.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2_youth["male"].fillna(df2_youth["male"].mean(), inplace=True)
/tmp/ipykernel_458/3933844224.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2_youth["owid_region_y"].fillna(df2_youth["owid_region_y"].mode()[0], inplace=True)

# Duplicate

In [ ]:
[
    df1_adult.duplicated().sum(),
    df2_youth.duplicated().sum(),
    df3_illiterate.duplicated().sum(),
    df4_GDP.duplicated().sum(),
    df5_schooling.duplicated().sum()
]

[np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0)]

# Describe

In [ ]:
[
    df1_adult.describe().T.sum(),
    df2_youth.describe().T.sum(),
    df3_illiterate.describe().T.sum(),
    df4_GDP.describe().T.sum(),
    df5_schooling.describe().T.sum()
    ]

[count    3450.000000
 mean     2081.197200
 std        32.512423
 min      1979.000000
 25%      2058.492390
 50%      2089.157580
 75%      2109.000000
 max      2123.000000
 dtype: float64,
 count    6006.000000
 mean     2178.290459
 std        44.543725
 min      1999.000000
 25%      2155.579473
 50%      2194.590000
 75%      2212.409690
 max      2223.000000
 dtype: float64,
 count    6177.000000
 mean     2086.084507
 std       112.979943
 min      1475.000000
 25%      2047.686219
 50%      2102.000000
 75%      2148.313780
 max      2223.000000
 dtype: float64,
 count     14480.000000
 mean      23850.031943
 std       23841.009186
 min        2500.822800
 25%        6519.726250
 50%       14721.597000
 75%       34602.047750
 max      176593.520000
 dtype: float64,
 count    2.146000e+04
 mean     9.752943e+07
 std      3.624671e+08
 min      3.087000e+03
 25%      2.480760e+06
 50%      8.761971e+06
 75%      5.221110e+07
 max      4.686813e+09
 dtype: float64]

# Year Filter 1990 to 2023

In [ ]:
df1_adult=df1_adult[(df1_adult['year']>= 1990) & (df1_adult['year'] <= 2023)]
df2_youth=df2_youth[(df2_youth['year']>= 1990) & (df2_youth['year'] <= 2023)]
df3_illiterate=df3_illiterate[(df3_illiterate['year']>= 1990) & (df3_illiterate['year'] <= 2023)]
df4_GDP=df4_GDP[(df4_GDP['year']>=1990) & (df4_GDP['year'] <= 2023)]
df5_schooling=df5_schooling[(df5_schooling['year']>= 1990) & (df5_schooling['year'] <= 2023)]

In [ ]:
df1_adult[df1_adult['year'] <= 2023]
df2_youth[df2_youth['year'] <= 2023]
df3_illiterate[df3_illiterate['year'] <= 2023]
df4_GDP[df4_GDP['year'] <= 2023]
df5_schooling[df5_schooling['year'] <= 2023]

,Country_B,code,year,literacy_rate,youth_adult_yr_edu,population_historical,owid_region_b
25,Afghanistan,AFG,1990,79.13807,2.060000,12045664.0,Asia
26,Afghanistan,AFG,1995,79.13807,2.400000,17065837.0,Asia
27,Afghanistan,AFG,2000,79.13807,3.030000,20130334.0,Asia
28,Afghanistan,AFG,2005,79.13807,3.320000,24404575.0,Asia
29,Afghanistan,AFG,2010,79.13807,3.930000,28284088.0,Asia
...,...,...,...,...,...,...,...
5360,Zimbabwe,ZWE,2005,79.13807,7.650000,12483433.0,Africa
5361,Zimbabwe,ZWE,2010,79.13807,7.860000,13356551.0,Africa
5362,Zimbabwe,ZWE,2015,79.13807,8.030000,14399008.0,Africa
5363,Zimbabwe,ZWE,2019,93.22755,3.815776,15271377.0,Africa
5364,Zimbabwe,ZWE,2020,79.13807,8.320000,15526887.0,Africa

In [ ]:
[
df1_adult.isnull().sum()/df1_adult.shape[0]*100,
df2_youth.isnull().sum()/df2_youth.shape[0]*100,
df3_illiterate.isnull().sum()/df3_illiterate.shape[0]*100,
df4_GDP.isnull().sum()/df4_GDP.shape[0]*100,
df5_schooling.isnull().sum()/df5_schooling.shape[0]*100
]

[Country_X                          0.000000
 code                              38.873239
 year                               0.000000
 adult_literacy_rate_population     0.000000
 dtype: float64,
 Country_Y         0.000000
 code             33.235121
 year              0.000000
 male              0.000000
 female            0.000000
 owid_region_y     0.000000
 dtype: float64,
 Country_Z           0.000000
 code               38.900634
 year                0.000000
 illiteracy_rate     0.000000
 literacy_rate       0.000000
 dtype: float64,
 Country_A         0.000000
 code              0.000000
 year              0.000000
 gdp_per_capita    0.000000
 owid_region_a     6.279301
 dtype: float64,
 Country_B                 0.000000
 code                     27.574906
 year                      0.000000
 literacy_rate             0.000000
 youth_adult_yr_edu        0.000000
 population_historical     0.000000
 owid_region_b            27.574906
 dtype: float64]

# Filter the year

In [ ]:
df1 = pd.merge(df1_adult, df2_youth, on="year", how="left")
df1

,Country_X,code_x,year,adult_literacy_rate_population,Country_Y,code_y,male,female,owid_region_y
0,Afghanistan,AFG,2011,31.00000,Afghanistan,AFG,62.00000,32.0000,Asia
1,Afghanistan,AFG,2011,31.00000,Albania,ALB,99.00000,99.0000,Europe
2,Afghanistan,AFG,2011,31.00000,Armenia,ARM,100.00000,100.0000,Asia
3,Afghanistan,AFG,2011,31.00000,Azerbaijan,AZE,100.00000,100.0000,Asia
4,Afghanistan,AFG,2011,31.00000,Bangladesh,BGD,76.00000,80.0000,Asia
...,...,...,...,...,...,...,...,...,...
79008,Zimbabwe,ZWE,2019,93.22755,Uruguay,URY,98.70000,99.3000,South America
79009,Zimbabwe,ZWE,2019,93.22755,Uzbekistan,UZB,100.00000,100.0000,Asia
79010,Zimbabwe,ZWE,2019,93.22755,Vietnam,VNM,99.00000,99.0000,Asia
79011,Zimbabwe,ZWE,2019,93.22755,World,OWID_WRL,93.74094,90.9163,Asia
79012,Zimbabwe,ZWE,2019,93.22755,Zimbabwe,ZWE,90.77383,94.2159,Africa

In [ ]:
import pandas as pd
df1.to_csv("df_Literacy.csv",index=False)

In [ ]:
df_Literacy = pd.read_csv('df_Literacy.csv')
df_Literacy

,Country_X,code_x,year,adult_literacy_rate_population,Country_Y,code_y,male,female,owid_region_y
0,Afghanistan,AFG,2011,31.00000,Afghanistan,AFG,62.00000,32.0000,Asia
1,Afghanistan,AFG,2011,31.00000,Albania,ALB,99.00000,99.0000,Europe
2,Afghanistan,AFG,2011,31.00000,Armenia,ARM,100.00000,100.0000,Asia
3,Afghanistan,AFG,2011,31.00000,Azerbaijan,AZE,100.00000,100.0000,Asia
4,Afghanistan,AFG,2011,31.00000,Bangladesh,BGD,76.00000,80.0000,Asia
...,...,...,...,...,...,...,...,...,...
79008,Zimbabwe,ZWE,2019,93.22755,Uruguay,URY,98.70000,99.3000,South America
79009,Zimbabwe,ZWE,2019,93.22755,Uzbekistan,UZB,100.00000,100.0000,Asia
79010,Zimbabwe,ZWE,2019,93.22755,Vietnam,VNM,99.00000,99.0000,Asia
79011,Zimbabwe,ZWE,2019,93.22755,World,OWID_WRL,93.74094,90.9163,Asia
79012,Zimbabwe,ZWE,2019,93.22755,Zimbabwe,ZWE,90.77383,94.2159,Africa

In [ ]:
df2=pd.read_csv('Illiterate.csv')

In [ ]:
df3_illiterate

        Country_Z code  year  illiteracy_rate  literacy_rate
2     Afghanistan  AFG  2011        69.000000       31.00000
3     Afghanistan  AFG  2015        66.246155       33.75384
4     Afghanistan  AFG  2021        63.000000       37.00000
6         Albania  ALB  2001         1.000000       99.00000
7         Albania  ALB  2008         4.000000       96.00000
...           ...  ...   ...              ...            ...
2051       Zambia  ZMB  2002        31.000000       69.00000
2052       Zambia  ZMB  2010        17.000000       83.00000
2053       Zambia  ZMB  2018        28.867699       71.13230
2057     Zimbabwe  ZWE  1992        16.000000       84.00000
2058     Zimbabwe  ZWE  2019         6.772453       93.22755

[1419 rows x 5 columns]

In [ ]:
import pandas as pd
df3_illiterate.to_csv("df_Illiteracy.csv",index=False)

In [ ]:
df3 = pd.merge(df4_GDP, df5_schooling, on="year", how="left")
df3

,Country_A,code_x,year,gdp_per_capita,owid_region_a,Country_B,code_y,literacy_rate,youth_adult_yr_edu,population_historical,owid_region_b
0,Afghanistan,AFG,2000,1617.8264,Asia,Afghanistan,AFG,79.13807,3.030000,2.013033e+07,Asia
1,Afghanistan,AFG,2000,1617.8264,Asia,Africa,NaN,79.13807,5.012495,8.305828e+08,NaN
2,Afghanistan,AFG,2000,1617.8264,Asia,Albania,ALB,79.13807,9.930000,3.166147e+06,Europe
3,Afghanistan,AFG,2000,1617.8264,Asia,Algeria,DZA,79.13807,6.060000,3.090389e+07,Africa
4,Afghanistan,AFG,2000,1617.8264,Asia,Argentina,ARG,79.13807,9.080000,3.721399e+07,South America
...,...,...,...,...,...,...,...,...,...,...,...
443550,Zimbabwe,ZWE,2023,5218.0225,Africa,Sub-Saharan Africa (WB),NaN,68.19624,3.815776,9.752739e+07,NaN
443551,Zimbabwe,ZWE,2023,5218.0225,Africa,Tunisia,TUN,86.24682,3.815776,1.220043e+07,Africa
443552,Zimbabwe,ZWE,2023,5218.0225,Africa,United Arab Emirates,ARE,98.00000,3.815776,1.064209e+07,Asia
443553,Zimbabwe,ZWE,2023,5218.0225,Africa,Upper-middle-income countries,NaN,95.61952,3.815776,2.852871e+09,NaN
443554,Zimbabwe,ZWE,2023,5218.0225,Africa,Vanuatu,VUT,87.96032,3.815776,3.204220e+05,Oceania

In [ ]:
import pandas as pd
df3.to_csv("df_Gdp_Schooling.csv",index=False)

# Literacy Gender Gap
Highlights the disparity between male and female literacy rates.

In [ ]:
df_Literacy = pd.read_csv('df_Literacy.csv')
df_Literacy['Literacy_Gap'] = df_Literacy['male'] - df_Literacy['female']
df_Literacy

,Country_X,code_x,year,adult_literacy_rate_population,Country_Y,code_y,male,female,owid_region_y,Literacy_Gap
0,Afghanistan,AFG,2011,31.00000,Afghanistan,AFG,62.00000,32.0000,Asia,30.00000
1,Afghanistan,AFG,2011,31.00000,Albania,ALB,99.00000,99.0000,Europe,0.00000
2,Afghanistan,AFG,2011,31.00000,Armenia,ARM,100.00000,100.0000,Asia,0.00000
3,Afghanistan,AFG,2011,31.00000,Azerbaijan,AZE,100.00000,100.0000,Asia,0.00000
4,Afghanistan,AFG,2011,31.00000,Bangladesh,BGD,76.00000,80.0000,Asia,-4.00000
...,...,...,...,...,...,...,...,...,...,...
79008,Zimbabwe,ZWE,2019,93.22755,Uruguay,URY,98.70000,99.3000,South America,-0.60000
79009,Zimbabwe,ZWE,2019,93.22755,Uzbekistan,UZB,100.00000,100.0000,Asia,0.00000
79010,Zimbabwe,ZWE,2019,93.22755,Vietnam,VNM,99.00000,99.0000,Asia,0.00000
79011,Zimbabwe,ZWE,2019,93.22755,World,OWID_WRL,93.74094,90.9163,Asia,2.82464
79012,Zimbabwe,ZWE,2019,93.22755,Zimbabwe,ZWE,90.77383,94.2159,Africa,-3.44207

# GDP per Schooling Year
Helps analyze economic output per year of education.

In [ ]:
df_Gdp_Schooling = pd.read_csv('df_Gdp_Schooling.csv')
df_Gdp_Schooling['GDP_Gap'] = df_Gdp_Schooling['gdp_per_capita'] / df_Gdp_Schooling['youth_adult_yr_edu']
df_Gdp_Schooling

,Country_A,code_x,year,gdp_per_capita,owid_region_a,Country_B,code_y,literacy_rate,youth_adult_yr_edu,population_historical,owid_region_b,GDP_Gap
0,Afghanistan,AFG,2000,1617.8264,Asia,Afghanistan,AFG,79.13807,3.030000,2.013033e+07,Asia,533.936106
1,Afghanistan,AFG,2000,1617.8264,Asia,Africa,NaN,79.13807,5.012495,8.305828e+08,NaN,322.758706
2,Afghanistan,AFG,2000,1617.8264,Asia,Albania,ALB,79.13807,9.930000,3.166147e+06,Europe,162.923102
3,Afghanistan,AFG,2000,1617.8264,Asia,Algeria,DZA,79.13807,6.060000,3.090389e+07,Africa,266.968053
4,Afghanistan,AFG,2000,1617.8264,Asia,Argentina,ARG,79.13807,9.080000,3.721399e+07,South America,178.174714
...,...,...,...,...,...,...,...,...,...,...,...,...
443550,Zimbabwe,ZWE,2023,5218.0225,Africa,Sub-Saharan Africa (WB),NaN,68.19624,3.815776,9.752739e+07,NaN,1367.486555
443551,Zimbabwe,ZWE,2023,5218.0225,Africa,Tunisia,TUN,86.24682,3.815776,1.220043e+07,Africa,1367.486555
443552,Zimbabwe,ZWE,2023,5218.0225,Africa,United Arab Emirates,ARE,98.00000,3.815776,1.064209e+07,Asia,1367.486555
443553,Zimbabwe,ZWE,2023,5218.0225,Africa,Upper-middle-income countries,NaN,95.61952,3.815776,2.852871e+09,NaN,1367.486555
443554,Zimbabwe,ZWE,2023,5218.0225,Africa,Vanuatu,VUT,87.96032,3.815776,3.204220e+05,Oceania,1367.486555

# Education Index
Measures education quality by considering both access (literacy) and duration (schooling).

In [ ]:
df_Gdp_Schooling["Education_Index"] = (df_Gdp_Schooling["literacy_rate"] +  df_Gdp_Schooling["youth_adult_yr_edu"])
df_Gdp_Schooling

,Country_A,code_x,year,gdp_per_capita,owid_region_a,Country_B,code_y,literacy_rate,youth_adult_yr_edu,population_historical,owid_region_b,GDP_Gap,Education_Index
0,Afghanistan,AFG,2000,1617.8264,Asia,Afghanistan,AFG,79.13807,3.030000,2.013033e+07,Asia,533.936106,82.168070
1,Afghanistan,AFG,2000,1617.8264,Asia,Africa,NaN,79.13807,5.012495,8.305828e+08,NaN,322.758706,84.150565
2,Afghanistan,AFG,2000,1617.8264,Asia,Albania,ALB,79.13807,9.930000,3.166147e+06,Europe,162.923102,89.068070
3,Afghanistan,AFG,2000,1617.8264,Asia,Algeria,DZA,79.13807,6.060000,3.090389e+07,Africa,266.968053,85.198070
4,Afghanistan,AFG,2000,1617.8264,Asia,Argentina,ARG,79.13807,9.080000,3.721399e+07,South America,178.174714,88.218070
...,...,...,...,...,...,...,...,...,...,...,...,...,...
443550,Zimbabwe,ZWE,2023,5218.0225,Africa,Sub-Saharan Africa (WB),NaN,68.19624,3.815776,9.752739e+07,NaN,1367.486555,72.012016
443551,Zimbabwe,ZWE,2023,5218.0225,Africa,Tunisia,TUN,86.24682,3.815776,1.220043e+07,Africa,1367.486555,90.062596
443552,Zimbabwe,ZWE,2023,5218.0225,Africa,United Arab Emirates,ARE,98.00000,3.815776,1.064209e+07,Asia,1367.486555,101.815776
443553,Zimbabwe,ZWE,2023,5218.0225,Africa,Upper-middle-income countries,NaN,95.61952,3.815776,2.852871e+09,NaN,1367.486555,99.435296
443554,Zimbabwe,ZWE,2023,5218.0225,Africa,Vanuatu,VUT,87.96032,3.815776,3.204220e+05,Oceania,1367.486555,91.776096

# Youth Literacy Average
Provides a single indicator for overall youth literacy.

In [ ]:
df_Literacy["Youth_Literacy_Avg"] = (
df_Literacy["male"] + df_Literacy["female"]) / 2
df_Literacy

,Country_X,code_x,year,adult_literacy_rate_population,Country_Y,code_y,male,female,owid_region_y,Youth_Literacy_Avg
0,Afghanistan,AFG,2011,31.00000,Afghanistan,AFG,62.00000,32.0000,Asia,47.000000
1,Afghanistan,AFG,2011,31.00000,Albania,ALB,99.00000,99.0000,Europe,99.000000
2,Afghanistan,AFG,2011,31.00000,Armenia,ARM,100.00000,100.0000,Asia,100.000000
3,Afghanistan,AFG,2011,31.00000,Azerbaijan,AZE,100.00000,100.0000,Asia,100.000000
4,Afghanistan,AFG,2011,31.00000,Bangladesh,BGD,76.00000,80.0000,Asia,78.000000
...,...,...,...,...,...,...,...,...,...,...
79008,Zimbabwe,ZWE,2019,93.22755,Uruguay,URY,98.70000,99.3000,South America,99.000000
79009,Zimbabwe,ZWE,2019,93.22755,Uzbekistan,UZB,100.00000,100.0000,Asia,100.000000
79010,Zimbabwe,ZWE,2019,93.22755,Vietnam,VNM,99.00000,99.0000,Asia,99.000000
79011,Zimbabwe,ZWE,2019,93.22755,World,OWID_WRL,93.74094,90.9163,Asia,92.328620
79012,Zimbabwe,ZWE,2019,93.22755,Zimbabwe,ZWE,90.77383,94.2159,Africa,92.494865

# Adult Literacy rate
Adult literacy for male and female

In [ ]:
df_Literacy["Adult_Literacy_both"] = (
df_Literacy["male"] + df_Literacy["female"])
df_Literacy

,Country_X,code_x,year,adult_literacy_rate_population,Country_Y,code_y,male,female,owid_region_y,Youth_Literacy_Avg,Adult_Literacy_both
0,Afghanistan,AFG,2011,31.00000,Afghanistan,AFG,62.00000,32.0000,Asia,47.000000,94.00000
1,Afghanistan,AFG,2011,31.00000,Albania,ALB,99.00000,99.0000,Europe,99.000000,198.00000
2,Afghanistan,AFG,2011,31.00000,Armenia,ARM,100.00000,100.0000,Asia,100.000000,200.00000
3,Afghanistan,AFG,2011,31.00000,Azerbaijan,AZE,100.00000,100.0000,Asia,100.000000,200.00000
4,Afghanistan,AFG,2011,31.00000,Bangladesh,BGD,76.00000,80.0000,Asia,78.000000,156.00000
...,...,...,...,...,...,...,...,...,...,...,...
79008,Zimbabwe,ZWE,2019,93.22755,Uruguay,URY,98.70000,99.3000,South America,99.000000,198.00000
79009,Zimbabwe,ZWE,2019,93.22755,Uzbekistan,UZB,100.00000,100.0000,Asia,100.000000,200.00000
79010,Zimbabwe,ZWE,2019,93.22755,Vietnam,VNM,99.00000,99.0000,Asia,99.000000,198.00000
79011,Zimbabwe,ZWE,2019,93.22755,World,OWID_WRL,93.74094,90.9163,Asia,92.328620,184.65724
79012,Zimbabwe,ZWE,2019,93.22755,Zimbabwe,ZWE,90.77383,94.2159,Africa,92.494865,184.98973

# Aaverage Youth population for Schooling based on population

In [ ]:
df_Gdp_Schooling["youth_population"] = (
df_Gdp_Schooling['youth_adult_yr_edu'] / df_Gdp_Schooling['population_historical'])
df_Gdp_Schooling

,Country_A,code_x,year,gdp_per_capita,owid_region_a,Country_B,code_y,literacy_rate,youth_adult_yr_edu,population_historical,owid_region_b,GDP_Gap,Education_Index,youth_population
0,Afghanistan,AFG,2000,1617.8264,Asia,Afghanistan,AFG,79.13807,3.030000,2.013033e+07,Asia,533.936106,82.168070,1.505191e-07
1,Afghanistan,AFG,2000,1617.8264,Asia,Africa,NaN,79.13807,5.012495,8.305828e+08,NaN,322.758706,84.150565,6.034913e-09
2,Afghanistan,AFG,2000,1617.8264,Asia,Albania,ALB,79.13807,9.930000,3.166147e+06,Europe,162.923102,89.068070,3.136304e-06
3,Afghanistan,AFG,2000,1617.8264,Asia,Algeria,DZA,79.13807,6.060000,3.090389e+07,Africa,266.968053,85.198070,1.960918e-07
4,Afghanistan,AFG,2000,1617.8264,Asia,Argentina,ARG,79.13807,9.080000,3.721399e+07,South America,178.174714,88.218070,2.439943e-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
443550,Zimbabwe,ZWE,2023,5218.0225,Africa,Sub-Saharan Africa (WB),NaN,68.19624,3.815776,9.752739e+07,NaN,1367.486555,72.012016,3.912517e-08
443551,Zimbabwe,ZWE,2023,5218.0225,Africa,Tunisia,TUN,86.24682,3.815776,1.220043e+07,Africa,1367.486555,90.062596,3.127574e-07
443552,Zimbabwe,ZWE,2023,5218.0225,Africa,United Arab Emirates,ARE,98.00000,3.815776,1.064209e+07,Asia,1367.486555,101.815776,3.585552e-07
443553,Zimbabwe,ZWE,2023,5218.0225,Africa,Upper-middle-income countries,NaN,95.61952,3.815776,2.852871e+09,NaN,1367.486555,99.435296,1.337521e-09
443554,Zimbabwe,ZWE,2023,5218.0225,Africa,Vanuatu,VUT,87.96032,3.815776,3.204220e+05,Oceania,1367.486555,91.776096,1.190860e-05

# Average of Literacy and Illiterate

In [ ]:
df3_illiterate["Avg_literacy_illiteracy"] = (
df3_illiterate['literacy_rate'] + df3_illiterate['illiteracy_rate']/2 )
df3_illiterate

,Country_Z,code,year,illiteracy_rate,literacy_rate,Avg_literacy_illiteracy
2,Afghanistan,AFG,2011,69.000000,31.00000,65.500000
3,Afghanistan,AFG,2015,66.246155,33.75384,66.876917
4,Afghanistan,AFG,2021,63.000000,37.00000,68.500000
6,Albania,ALB,2001,1.000000,99.00000,99.500000
7,Albania,ALB,2008,4.000000,96.00000,98.000000
...,...,...,...,...,...,...
2051,Zambia,ZMB,2002,31.000000,69.00000,84.500000
2052,Zambia,ZMB,2010,17.000000,83.00000,91.500000
2053,Zambia,ZMB,2018,28.867699,71.13230,85.566149
2057,Zimbabwe,ZWE,1992,16.000000,84.00000,92.000000
2058,Zimbabwe,ZWE,2019,6.772453,93.22755,96.613777

# Connection between python & SQL

In [ ]:
import sqlite3
import pandas as pd
conn = sqlite3.connect('Global.db')
print("Connected to in-memory database")

Connected to in-memory database

# Table 1 Creation of Literacy Rates

In [ ]:
cursor=conn.cursor()
cursor.execute('''
    Create table Literacy_rates(
     Country_X varchar(50),
     code_x varchar(50),
     year int,
     adult_literacy_rate_population float,
     Country_Y varchar(50),
     code_y varchar(50),
     male float,
     female float,
     owid_region_y varchar(50)

    )
''')

OperationalError: table Literacy_rates already exists

# Insert Values

In [ ]:
insert_query = """INSERT into Literacy_rates(Country_X,code_x, year,adult_literacy_rate_population,Country_Y,code_y, male,female,owid_region_y)
 VALUES (?,?,?,?,?,?,?,?,?)"""

for i, row in df_Literacy.iterrows():
    values = (row['Country_X'],row['code_x'],row['year'],row['adult_literacy_rate_population'],row['Country_Y'],row['code_y'],
              row['male'],row['female'],row['owid_region_y'])
    cursor.execute(insert_query,values)
conn.commit()

# Inserted After Viewing

In [ ]:
import pandas as pd
cursor.execute("select * from Literacy_rates")
rows = cursor.fetchall()
columns = [i[0] for i in cursor.description]
df = pd.DataFrame(rows,columns=columns)
df.head()

,Country_X,code_x,year,adult_literacy_rate_population,Country_Y,code_y,male,female,owid_region_y
0,Afghanistan,AFG,2011,31.0,Afghanistan,AFG,62.0,32.0,Asia
1,Afghanistan,AFG,2011,31.0,Albania,ALB,99.0,99.0,Europe
2,Afghanistan,AFG,2011,31.0,Armenia,ARM,100.0,100.0,Asia
3,Afghanistan,AFG,2011,31.0,Azerbaijan,AZE,100.0,100.0,Asia
4,Afghanistan,AFG,2011,31.0,Bangladesh,BGD,76.0,80.0,Asia

# Table 2 Creation of Illiteracy Population

In [ ]:
cursor=conn.cursor()
cursor.execute('''
    Create table Illiteracy_population(
     Country_Z varchar(50),
     code varchar(50),
     year int,
     illiteracy_rate float,
     literacy_rate float

    )
''')

# Insert Values

In [ ]:
insert_query = """INSERT into Illiteracy_population(Country_Z, code, year,illiteracy_rate,literacy_rate)
 VALUES (?,?,?,?,?)"""

for i, row in df3_illiterate.iterrows():
    values = (row['Country_Z'],row['code'],row['year'],row['illiteracy_rate'],row['literacy_rate'])
    cursor.execute(insert_query,values)
conn.commit()

# Insert After Viewing

In [ ]:
import pandas as pd
cursor.execute("select * from Illiteracy_population")
rows = cursor.fetchall()
columns = [i[0] for i in cursor.description]
df = pd.DataFrame(rows,columns=columns)
df.head()

     Country_Z code  year  illiteracy_rate  literacy_rate
0  Afghanistan  AFG  2011        69.000000       31.00000
1  Afghanistan  AFG  2015        66.246155       33.75384
2  Afghanistan  AFG  2021        63.000000       37.00000
3      Albania  ALB  2001         1.000000       99.00000
4      Albania  ALB  2008         4.000000       96.00000

# Table 3 Creation of GDP & Schooling

In [ ]:
cursor=conn.cursor()
cursor.execute('''
    Create table Gdp_Schooling (
     Country_A varchar(50),
     code_x varchar(50),
     year int,
     gdp_per_capita float,
     owid_region_a varchar(50),
     Country_B varchar(50),
     code_y varchar(50),
     literacy_rate float,
     youth_adult_yr_edu float,
     population_historical float,
     owid_region_b varchar(50)

    )
''')

# Insert Values

In [ ]:
insert_query = """INSERT into Gdp_Schooling (Country_A,code_x,year,gdp_per_capita,owid_region_a,Country_B,code_y,literacy_rate,youth_adult_yr_edu,population_historical,owid_region_b)
 VALUES (?,?,?,?,?,?,?,?,?,?,?)"""

for i, row in df_Gdp_Schooling.iterrows():
    values = (row['Country_A'],row['code_x'],row['year'],row['gdp_per_capita'],row['owid_region_a'],row['Country_B'],row['code_y'],row['literacy_rate'],row['youth_adult_yr_edu'],row['population_historical'],row['owid_region_b'])
    cursor.execute(insert_query,values)
conn.commit()

# Insert After Viewing

In [ ]:
import pandas as pd
cursor.execute("select * from Gdp_Schooling")
rows = cursor.fetchall()
columns = [i[0] for i in cursor.description]
df = pd.DataFrame(rows,columns=columns)
df.head()

,Country_A,code_x,year,gdp_per_capita,owid_region_a,Country_B,code_y,literacy_rate,youth_adult_yr_edu,population_historical,owid_region_b
0,Afghanistan,AFG,2000,1617.8264,Asia,Afghanistan,AFG,79.13807,3.030000,20130334.0,Asia
1,Afghanistan,AFG,2000,1617.8264,Asia,Africa,None,79.13807,5.012495,830582806.0,None
2,Afghanistan,AFG,2000,1617.8264,Asia,Albania,ALB,79.13807,9.930000,3166147.0,Europe
3,Afghanistan,AFG,2000,1617.8264,Asia,Algeria,DZA,79.13807,6.060000,30903894.0,Africa
4,Afghanistan,AFG,2000,1617.8264,Asia,Argentina,ARG,79.13807,9.080000,37213986.0,South America

# SQL QUERIES

 # literacy_rates
 1. Get top 5 countries with highest adult literacy in 2020.

In [ ]:
import pandas as pd
pd.read_sql("""SELECT country_x, adult_literacy_rate_population
    FROM literacy_rates
    WHERE year = 2020
    ORDER BY  adult_literacy_rate_population DESC
    LIMIT 5;""", conn)

  Country_X  adult_literacy_rate_population
0   Armenia                           100.0
1   Armenia                           100.0
2   Armenia                           100.0
3   Armenia                           100.0
4   Armenia                           100.0

 2. Find countries where female youth literacy < 80%

In [ ]:
pd.read_sql("""SELECT country_Y, female
    FROM literacy_rates
    WHERE female < 80
    ORDER BY  female DESC
    ;""", conn)

                               Country_Y    female
0      Middle East and North Africa (WB)  79.90238
1      Middle East and North Africa (WB)  79.90238
2      Middle East and North Africa (WB)  79.90238
3      Middle East and North Africa (WB)  79.90238
4      Middle East and North Africa (WB)  79.90238
...                                  ...       ...
41083                               Chad   9.00000
41084                               Chad   9.00000
41085                               Chad   9.00000
41086                               Chad   9.00000
41087                               Chad   9.00000

[41088 rows x 2 columns]

3.Average adult literacy per continent (owid region).

In [ ]:
pd.read_sql("""SELECT owid_region_y, AVG(adult_literacy_rate_population) AS avg_adult_literacy
    FROM Literacy_rates
    GROUP BY owid_region_y;""", conn)

   owid_region_y  avg_adult_literacy
0         Africa           81.154919
1           Asia           80.808227
2         Europe           80.897648
3  North America           81.778816
4        Oceania           81.802196
5  South America           81.661646

# illiteracy_population

In [ ]:
df_Illiteracy = pd.read_csv("/content/df_Illiteracy.csv")
df_Illiteracy.columns

Index(['Country_Z', 'code', 'year', 'illiteracy_rate', 'literacy_rate'], dtype='object')

4.Countries with illiteracy % > 20% in 2000.

In [ ]:
pd.read_sql("""
select
Country_Z,illiteracy_rate
FROM illiteracy_population
where illiteracy_rate > 20
and year = 2000
;""", conn
)

                                            Country_Z  illiteracy_rate
0                                             Burundi        41.000000
1                                            Cameroon        32.000000
2                            Central African Republic        49.000000
3                     Central and Southern Asia (SDG)        39.916970
4                                                Chad        74.000000
5                                             Comoros        32.000000
6                                       Cote d'Ivoire        51.000000
7                                              Gambia        63.000000
8                                               Ghana        42.000000
9                                       Guinea-Bissau        59.000000
10                                               Iraq        26.000000
11                                               Laos        30.000000
12                               Low-income countries        48.601340
13                      Lower-middle-income countries        37.197690
14                                         Madagascar        29.000000
15                                         Mauritania        49.000000
16                  Middle East and North Africa (WB)        30.598412
17                            Middle-income countries        21.022774
18             Northern Africa and Western Asia (SDG)        27.835136
19  Oceania (excluding Australia and New Zealand) ...        34.648680
20                                   Papua New Guinea        43.000000
21                                             Rwanda        35.000000
22                                       Saudi Arabia        21.000000
23                                    South Asia (WB)        42.349420
24                           Sub-Saharan Africa (SDG)        43.609400
25                            Sub-Saharan Africa (WB)        43.372450
26                                              Sudan        39.000000
27                                               Togo        47.000000

5.Trend of illiteracy % for India (2000–2020).

In [ ]:
pd.read_sql("""
select
Country_Z,illiteracy_rate, year
FROM illiteracy_population
where Country_Z = 'India'
and year >= 2000 and year <= 2020
order by year;
""", conn
)

  Country_Z  illiteracy_rate  year
0     India             39.0  2001
1     India             37.0  2006
2     India             31.0  2011

 6. Top 10 countries with largest illiterate population in the last year.

In [ ]:
pd.read_sql("""
SELECT
Country_Z,illiteracy_rate,year
FROM illiteracy_population
WHERE year = (SELECT MAX(year) FROM illiteracy_population)
ORDER BY illiteracy_rate DESC
LIMIT 10;
""",conn
 )

                                Country_Z  illiteracy_rate  year
0                                 Senegal        49.644180  2023
1                    Low-income countries        36.961470  2023
2                 Sub-Saharan Africa (WB)        31.803757  2023
3                Sub-Saharan Africa (SDG)        31.497803  2023
4                         South Asia (WB)        24.991150  2023
5         Central and Southern Asia (SDG)        23.485687  2023
6           Lower-middle-income countries        22.368180  2023
7       Middle East and North Africa (WB)        19.050858  2023
8  Northern Africa and Western Asia (SDG)        18.474640  2023
9                                   India        18.000000  2023

# GDP_Schooling

    7. Find countries with avg_years_schooling > 7 and gdp_per_capita < 5000.

In [ ]:
pd.read_sql("""
SELECT
Country_B,youth_adult_yr_edu,gdp_per_capita
FROM Gdp_Schooling
WHERE youth_adult_yr_edu > 7 AND gdp_per_capita < 5000;
""",conn )

       Country_B  youth_adult_yr_edu  gdp_per_capita
0        Albania                9.93       1617.8264
1      Argentina                9.08       1617.8264
2      Australia               11.37       1617.8264
3        Austria                9.43       1617.8264
4       Barbados                9.23       1617.8264
...          ...                 ...             ...
31483    Uruguay                8.76       4527.7197
31484  Venezuela                9.33       4527.7197
31485    Vietnam                8.35       4527.7197
31486     Zambia                8.37       4527.7197
31487   Zimbabwe                8.32       4527.7197

[31488 rows x 3 columns]

 8. Rank countries by GDP per schooling for the year 2020.

In [ ]:
pd.read_sql("""
SELECT
gdp_per_capita / youth_adult_yr_edu as gdp_per_schooling,
rank() over( order by gdp_per_capita /youth_adult_yr_edu desc) as rank
FROM Gdp_Schooling
where year = 2020;
""",conn)

       gdp_per_schooling   rank
0           42718.957237      1
1           38122.710526      2
2           36581.867606      3
3           34033.870674      4
4           34033.870674      4
...                  ...    ...
36459          78.445228  36460
36460          77.385158  36461
36461          76.184058  36462
36462          75.348706  36463
36463          75.019672  36464

[36464 rows x 2 columns]

9. Find global average schooling years per year.

In [ ]:
pd.read_sql("""
SELECT year,
avg(youth_adult_yr_edu) as "global avg_schooling"
FROM Gdp_Schooling
GROUP BY year
ORDER BY year;
""",conn)

    year  global avg_schooling
0   1990              6.253986
1   1991              3.815776
2   1992              3.815776
3   1993              3.815776
4   1994              3.815776
5   1995              6.715947
6   1996              3.815776
7   1997              3.815776
8   1998              3.815776
9   1999              3.815776
10  2000              6.687851
11  2001              3.815776
12  2002              3.815776
13  2003              3.815776
14  2004              3.815776
15  2005              7.432307
16  2006              3.815776
17  2007              3.815776
18  2008              3.815776
19  2009              3.815776
20  2010              7.704736
21  2011              3.815776
22  2012              3.815776
23  2013              3.815776
24  2014              3.815776
25  2015              8.350228
26  2016              3.815776
27  2017              3.815776
28  2018              3.815776
29  2019              3.815776
30  2020              8.720901
31  2021              3.815776
32  2022              3.815776
33  2023              3.815776

# Join Queries

   10. List top 10 countries in 2020 with highest GDP per capita but lowest average years of schooling(less than 6).

In [ ]:
pd.read_sql("""
SELECT
g.Country_A as country, g.year,g.gdp_per_capita,g.youth_adult_yr_edu
FROM Gdp_Schooling g
where g.year = 2020
and g.youth_adult_yr_edu < 6
order by g.gdp_per_capita desc
limit 10;
""",conn)

      country  year  gdp_per_capita  youth_adult_yr_edu
0  Luxembourg  2020       129865.63            5.690000
1  Luxembourg  2020       129865.63            5.050000
2  Luxembourg  2020       129865.63            5.810000
3  Luxembourg  2020       129865.63            4.640000
4  Luxembourg  2020       129865.63            3.815776
5  Luxembourg  2020       129865.63            4.850000
6  Luxembourg  2020       129865.63            3.815776
7  Luxembourg  2020       129865.63            3.815776
8  Luxembourg  2020       129865.63            3.815776
9  Luxembourg  2020       129865.63            3.815776

  11. Show countries where the illiterate population is high despite having more than 10 average years of schooling.

In [ ]:
pd.read_sql("""
SELECT
G.Country_A as country,
g.year,g.youth_adult_yr_edu,i.illiteracy_rate
FROM Gdp_Schooling g
join illiteracy_population i
on g.code_x = i.code
and g.year = i.year
where g.youth_adult_yr_edu > 10
and i.illiteracy_rate > 20
order by i.illiteracy_rate desc;
""",conn)

           country  year  youth_adult_yr_edu  illiteracy_rate
0     Burkina Faso  2005               10.24             76.0
1     Burkina Faso  2005               11.71             76.0
2     Burkina Faso  2005               11.11             76.0
3     Burkina Faso  2005               10.77             76.0
4     Burkina Faso  2005               10.61             76.0
...            ...   ...                 ...              ...
2385        Turkey  1990               10.21             21.0
2386        Turkey  1990               10.46             21.0
2387        Turkey  1990               11.03             21.0
2388        Turkey  1990               10.54             21.0
2389        Turkey  1990               12.55             21.0

[2390 rows x 4 columns]

   12. Compare literacy rates and GDP per capita growth for a selected country over the last 20 years. (country of your choice)

In [ ]:
pd.read_sql("""
SELECT
g.year,g.gdp_per_capita,g.literacy_rate
FROM Gdp_Schooling g
where g.Country_A = 'India'
and g.year >= 2000 and g.year <= 2020
order by g.year;
""",conn)

      year  gdp_per_capita  literacy_rate
0     2000        3099.503       79.13807
1     2000        3099.503       79.13807
2     2000        3099.503       79.13807
3     2000        3099.503       79.13807
4     2000        3099.503       79.13807
...    ...             ...            ...
1555  2020        7399.531       79.13807
1556  2020        7399.531       79.13807
1557  2020        7399.531       79.13807
1558  2020        7399.531       79.13807
1559  2020        7399.531       79.13807

[1560 rows x 3 columns]

 13. Show the difference between youth literacy male and female rates for countries with GDP per capita above $30,000 in 2020.

In [ ]:
pd.read_sql("""
SELECT
    g.Country_A AS country,
    g.gdp_per_capita,
    l.male AS male_literacy_rate,
    l.female AS female_literacy_rate,
    (l.male - l.female) AS literacy_gap
FROM Gdp_Schooling g
JOIN Literacy_rates l
    ON g.code_x = l.code_x
    AND g.year = l.year
WHERE g.year = 2020
  AND g.gdp_per_capita > 30000
ORDER BY literacy_gap DESC;
""",conn)

,country,gdp_per_capita,male_literacy_rate,female_literacy_rate,literacy_gap
0,Kuwait,49372.82,76.00,65.00,11.00
1,Kuwait,49372.82,76.00,65.00,11.00
2,Kuwait,49372.82,76.00,65.00,11.00
3,Kuwait,49372.82,76.00,65.00,11.00
4,Kuwait,49372.82,76.00,65.00,11.00
...,...,...,...,...,...
43855,Spain,41553.45,44.16,60.92,-16.76
43856,Spain,41553.45,44.16,60.92,-16.76
43857,Spain,41553.45,44.16,60.92,-16.76
43858,Spain,41553.45,44.16,60.92,-16.76
43859,Spain,41553.45,44.16,60.92,-16.76